// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user_address.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	IsMainAddress bool                   `protobuf:"varint,4,opt,name=is_main_address,json=isMainAddress,proto3" json:"is_main_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddress) Reset() {
	*x = ListAddress{}
	mi := &file_user_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddress) ProtoMessage() {}

func (x *ListAddress) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddress.ProtoReflect.Descriptor instead.
func (*ListAddress) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{0}
}

func (x *ListAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListAddress) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListAddress) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ListAddress) GetIsMainAddress() bool {
	if x != nil {
		return x.IsMainAddress
	}
	return false
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	IsMainAddress bool                   `protobuf:"varint,2,opt,name=is_main_address,json=isMainAddress,proto3" json:"is_main_address,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	X             float64                `protobuf:"fixed64,6,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,7,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_user_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Address) GetIsMainAddress() bool {
	if x != nil {
		return x.IsMainAddress
	}
	return false
}

func (x *Address) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Address) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetAddressesByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesByTokenRequest) Reset() {
	*x = GetAddressesByTokenRequest{}
	mi := &file_user_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesByTokenRequest) ProtoMessage() {}

func (x *GetAddressesByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAddressesByTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{2}
}

type GetAddressByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressByIDRequest) Reset() {
	*x = GetAddressByIDRequest{}
	mi := &file_user_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByIDRequest) ProtoMessage() {}

func (x *GetAddressByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAddressByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAddressByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressByIDResponse) Reset() {
	*x = GetAddressByIDResponse{}
	mi := &file_user_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByIDResponse) ProtoMessage() {}

func (x *GetAddressByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAddressByIDResponse) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddressByIDResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetAddressesByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*ListAddress         `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesByTokenResponse) Reset() {
	*x = GetAddressesByTokenResponse{}
	mi := &file_user_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesByTokenResponse) ProtoMessage() {}

func (x *GetAddressesByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAddressesByTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddressesByTokenResponse) GetAddresses() []*ListAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IsMainAddress bool                   `protobuf:"varint,3,opt,name=is_main_address,json=isMainAddress,proto3" json:"is_main_address,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_user_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAddressRequest) GetIsMainAddress() bool {
	if x != nil {
		return x.IsMainAddress
	}
	return false
}

func (x *UpdateAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type UpdateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressResponse) Reset() {
	*x = UpdateAddressResponse{}
	mi := &file_user_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResponse) ProtoMessage() {}

func (x *UpdateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAddressResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	IsMainAddress bool                   `protobuf:"varint,2,opt,name=is_main_address,json=isMainAddress,proto3" json:"is_main_address,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_user_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAddressRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAddressRequest) GetIsMainAddress() bool {
	if x != nil {
		return x.IsMainAddress
	}
	return false
}

func (x *CreateAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_user_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAddressResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_user_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_user_address_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAddressResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAddressInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddressId     string                 `protobuf:"bytes,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressInfoRequest) Reset() {
	*x = GetAddressInfoRequest{}
	mi := &file_user_address_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressInfoRequest) ProtoMessage() {}

func (x *GetAddressInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAddressInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{12}
}

func (x *GetAddressInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAddressInfoRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

type GetAddressInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressInfoResponse) Reset() {
	*x = GetAddressInfoResponse{}
	mi := &file_user_address_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressInfoResponse) ProtoMessage() {}

func (x *GetAddressInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_address_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAddressInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_address_proto_rawDescGZIP(), []int{13}
}

func (x *GetAddressInfoResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_user_address_proto protoreflect.FileDescriptor

const file_user_address_proto_rawDesc = "" +
	"\n" +
	"\x12user_address.proto\x12\fuser_address\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"q\n" +
	"\vListAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12&\n" +
	"\x0fis_main_address\x18\x04 \x01(\bR\risMainAddress\"\xdc\x01\n" +
	"\aAddress\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12&\n" +
	"\x0fis_main_address\x18\x02 \x01(\bR\risMainAddress\x12 \n" +
	"\x05label\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05label\x12\x1d\n" +
	"\x04city\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04city\x12*\n" +
	"\vpostal_code\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x14R\n" +
	"postalCode\x12\f\n" +
	"\x01x\x18\x06 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x01R\x01y\"\x1c\n" +
	"\x1aGetAddressesByTokenRequest\"1\n" +
	"\x15GetAddressByIDRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"I\n" +
	"\x16GetAddressByIDResponse\x12/\n" +
	"\aaddress\x18\x01 \x01(\v2\x15.user_address.AddressR\aaddress\"V\n" +
	"\x1bGetAddressesByTokenResponse\x127\n" +
	"\taddresses\x18\x01 \x03(\v2\x19.user_address.ListAddressR\taddresses\"\x90\x01\n" +
	"\x14UpdateAddressRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12 \n" +
	"\x05title\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12&\n" +
	"\x0fis_main_address\x18\x03 \x01(\bR\risMainAddress\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"'\n" +
	"\x15UpdateAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"v\n" +
	"\x14CreateAddressRequest\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12&\n" +
	"\x0fis_main_address\x18\x02 \x01(\bR\risMainAddress\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"'\n" +
	"\x15CreateAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteAddressRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"'\n" +
	"\x15DeleteAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x15GetAddressInfoRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12'\n" +
	"\n" +
	"address_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taddressId\"I\n" +
	"\x16GetAddressInfoResponse\x12/\n" +
	"\aaddress\x18\x01 \x01(\v2\x15.user_address.AddressR\aaddress2\xeb\x05\n" +
	"\x0eAddressService\x12\x87\x01\n" +
	"\x13GetAddressesByToken\x12(.user_address.GetAddressesByTokenRequest\x1a).user_address.GetAddressesByTokenResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/addresses\x12}\n" +
	"\x0eGetAddressByID\x12#.user_address.GetAddressByIDRequest\x1a$.user_address.GetAddressByIDResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/users/addresses/{id}\x12x\n" +
	"\rCreateAddress\x12\".user_address.CreateAddressRequest\x1a#.user_address.CreateAddressResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/users/addresses\x12}\n" +
	"\rUpdateAddress\x12\".user_address.UpdateAddressRequest\x1a#.user_address.UpdateAddressResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/users/addresses/{id}\x12z\n" +
	"\rDeleteAddress\x12\".user_address.DeleteAddressRequest\x1a#.user_address.DeleteAddressResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/users/addresses/{id}\x12[\n" +
	"\x0eGetAddressInfo\x12#.user_address.GetAddressInfoRequest\x1a$.user_address.GetAddressInfoResponseB\x7f\n" +
	"\x10com.user_addressB\x10UserAddressProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03UXX\xaa\x02\vUserAddress\xca\x02\vUserAddress\xe2\x02\x17UserAddress\\GPBMetadata\xea\x02\vUserAddressb\x06proto3"

var (
	file_user_address_proto_rawDescOnce sync.Once
	file_user_address_proto_rawDescData []byte
)

func file_user_address_proto_rawDescGZIP() []byte {
	file_user_address_proto_rawDescOnce.Do(func() {
		file_user_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_address_proto_rawDesc), len(file_user_address_proto_rawDesc)))
	})
	return file_user_address_proto_rawDescData
}

var file_user_address_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_address_proto_goTypes = []any{
	(*ListAddress)(nil),                 // 0: user_address.ListAddress
	(*Address)(nil),                     // 1: user_address.Address
	(*GetAddressesByTokenRequest)(nil),  // 2: user_address.GetAddressesByTokenRequest
	(*GetAddressByIDRequest)(nil),       // 3: user_address.GetAddressByIDRequest
	(*GetAddressByIDResponse)(nil),      // 4: user_address.GetAddressByIDResponse
	(*GetAddressesByTokenResponse)(nil), // 5: user_address.GetAddressesByTokenResponse
	(*UpdateAddressRequest)(nil),        // 6: user_address.UpdateAddressRequest
	(*UpdateAddressResponse)(nil),       // 7: user_address.UpdateAddressResponse
	(*CreateAddressRequest)(nil),        // 8: user_address.CreateAddressRequest
	(*CreateAddressResponse)(nil),       // 9: user_address.CreateAddressResponse
	(*DeleteAddressRequest)(nil),        // 10: user_address.DeleteAddressRequest
	(*DeleteAddressResponse)(nil),       // 11: user_address.DeleteAddressResponse
	(*GetAddressInfoRequest)(nil),       // 12: user_address.GetAddressInfoRequest
	(*GetAddressInfoResponse)(nil),      // 13: user_address.GetAddressInfoResponse
}
var file_user_address_proto_depIdxs = []int32{
	1,  // 0: user_address.GetAddressByIDResponse.address:type_name -> user_address.Address
	0,  // 1: user_address.GetAddressesByTokenResponse.addresses:type_name -> user_address.ListAddress
	1,  // 2: user_address.GetAddressInfoResponse.address:type_name -> user_address.Address
	2,  // 3: user_address.AddressService.GetAddressesByToken:input_type -> user_address.GetAddressesByTokenRequest
	3,  // 4: user_address.AddressService.GetAddressByID:input_type -> user_address.GetAddressByIDRequest
	8,  // 5: user_address.AddressService.CreateAddress:input_type -> user_address.CreateAddressRequest
	6,  // 6: user_address.AddressService.UpdateAddress:input_type -> user_address.UpdateAddressRequest
	10, // 7: user_address.AddressService.DeleteAddress:input_type -> user_address.DeleteAddressRequest
	12, // 8: user_address.AddressService.GetAddressInfo:input_type -> user_address.GetAddressInfoRequest
	5,  // 9: user_address.AddressService.GetAddressesByToken:output_type -> user_address.GetAddressesByTokenResponse
	4,  // 10: user_address.AddressService.GetAddressByID:output_type -> user_address.GetAddressByIDResponse
	9,  // 11: user_address.AddressService.CreateAddress:output_type -> user_address.CreateAddressResponse
	7,  // 12: user_address.AddressService.UpdateAddress:output_type -> user_address.UpdateAddressResponse
	11, // 13: user_address.AddressService.DeleteAddress:output_type -> user_address.DeleteAddressResponse
	13, // 14: user_address.AddressService.GetAddressInfo:output_type -> user_address.GetAddressInfoResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_address_proto_init() }
func file_user_address_proto_init() {
	if File_user_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_address_proto_rawDesc), len(file_user_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_address_proto_goTypes,
		DependencyIndexes: file_user_address_proto_depIdxs,
		MessageInfos:      file_user_address_proto_msgTypes,
	}.Build()
	File_user_address_proto = out.File
	file_user_address_proto_goTypes = nil
	file_user_address_proto_depIdxs = nil
}
