// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: mau.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatService_SearchCatByName_FullMethodName = "/cat.CatService/SearchCatByName"
	CatService_GetLookALikeCat_FullMethodName = "/cat.CatService/GetLookALikeCat"
	CatService_CreateCat_FullMethodName       = "/cat.CatService/CreateCat"
	CatService_DeleteCat_FullMethodName       = "/cat.CatService/DeleteCat"
	CatService_UpdateCat_FullMethodName       = "/cat.CatService/UpdateCat"
	CatService_GetCatByID_FullMethodName      = "/cat.CatService/GetCatByID"
)

// CatServiceClient is the client API for CatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatServiceClient interface {
	SearchCatByName(ctx context.Context, in *SearchCatByNameRequest, opts ...grpc.CallOption) (*SearchCatByNameResponse, error)
	GetLookALikeCat(ctx context.Context, in *GetLookALikeCatRequest, opts ...grpc.CallOption) (*GetLookALikeCatResponse, error)
	CreateCat(ctx context.Context, in *CreateCatRequest, opts ...grpc.CallOption) (*CreateCatResponse, error)
	DeleteCat(ctx context.Context, in *DeleteCatRequest, opts ...grpc.CallOption) (*DeleteCatResponse, error)
	UpdateCat(ctx context.Context, in *UpdateCatRequest, opts ...grpc.CallOption) (*UpdateCatResponse, error)
	GetCatByID(ctx context.Context, in *GetCatByIDRequest, opts ...grpc.CallOption) (*GetCatByIDResponse, error)
}

type catServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatServiceClient(cc grpc.ClientConnInterface) CatServiceClient {
	return &catServiceClient{cc}
}

func (c *catServiceClient) SearchCatByName(ctx context.Context, in *SearchCatByNameRequest, opts ...grpc.CallOption) (*SearchCatByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCatByNameResponse)
	err := c.cc.Invoke(ctx, CatService_SearchCatByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetLookALikeCat(ctx context.Context, in *GetLookALikeCatRequest, opts ...grpc.CallOption) (*GetLookALikeCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLookALikeCatResponse)
	err := c.cc.Invoke(ctx, CatService_GetLookALikeCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CreateCat(ctx context.Context, in *CreateCatRequest, opts ...grpc.CallOption) (*CreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_CreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) DeleteCat(ctx context.Context, in *DeleteCatRequest, opts ...grpc.CallOption) (*DeleteCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCatResponse)
	err := c.cc.Invoke(ctx, CatService_DeleteCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UpdateCat(ctx context.Context, in *UpdateCatRequest, opts ...grpc.CallOption) (*UpdateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCatResponse)
	err := c.cc.Invoke(ctx, CatService_UpdateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetCatByID(ctx context.Context, in *GetCatByIDRequest, opts ...grpc.CallOption) (*GetCatByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatByIDResponse)
	err := c.cc.Invoke(ctx, CatService_GetCatByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServiceServer is the server API for CatService service.
// All implementations must embed UnimplementedCatServiceServer
// for forward compatibility.
type CatServiceServer interface {
	SearchCatByName(context.Context, *SearchCatByNameRequest) (*SearchCatByNameResponse, error)
	GetLookALikeCat(context.Context, *GetLookALikeCatRequest) (*GetLookALikeCatResponse, error)
	CreateCat(context.Context, *CreateCatRequest) (*CreateCatResponse, error)
	DeleteCat(context.Context, *DeleteCatRequest) (*DeleteCatResponse, error)
	UpdateCat(context.Context, *UpdateCatRequest) (*UpdateCatResponse, error)
	GetCatByID(context.Context, *GetCatByIDRequest) (*GetCatByIDResponse, error)
	mustEmbedUnimplementedCatServiceServer()
}

// UnimplementedCatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatServiceServer struct{}

func (UnimplementedCatServiceServer) SearchCatByName(context.Context, *SearchCatByNameRequest) (*SearchCatByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCatByName not implemented")
}
func (UnimplementedCatServiceServer) GetLookALikeCat(context.Context, *GetLookALikeCatRequest) (*GetLookALikeCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLookALikeCat not implemented")
}
func (UnimplementedCatServiceServer) CreateCat(context.Context, *CreateCatRequest) (*CreateCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCat not implemented")
}
func (UnimplementedCatServiceServer) DeleteCat(context.Context, *DeleteCatRequest) (*DeleteCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCat not implemented")
}
func (UnimplementedCatServiceServer) UpdateCat(context.Context, *UpdateCatRequest) (*UpdateCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCat not implemented")
}
func (UnimplementedCatServiceServer) GetCatByID(context.Context, *GetCatByIDRequest) (*GetCatByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatByID not implemented")
}
func (UnimplementedCatServiceServer) mustEmbedUnimplementedCatServiceServer() {}
func (UnimplementedCatServiceServer) testEmbeddedByValue()                    {}

// UnsafeCatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatServiceServer will
// result in compilation errors.
type UnsafeCatServiceServer interface {
	mustEmbedUnimplementedCatServiceServer()
}

func RegisterCatServiceServer(s grpc.ServiceRegistrar, srv CatServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatService_ServiceDesc, srv)
}

func _CatService_SearchCatByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCatByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).SearchCatByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_SearchCatByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).SearchCatByName(ctx, req.(*SearchCatByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetLookALikeCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLookALikeCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetLookALikeCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetLookALikeCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetLookALikeCat(ctx, req.(*GetLookALikeCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CreateCat(ctx, req.(*CreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_DeleteCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).DeleteCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_DeleteCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).DeleteCat(ctx, req.(*DeleteCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UpdateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UpdateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UpdateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UpdateCat(ctx, req.(*UpdateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetCatByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetCatByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetCatByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetCatByID(ctx, req.(*GetCatByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatService_ServiceDesc is the grpc.ServiceDesc for CatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cat.CatService",
	HandlerType: (*CatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchCatByName",
			Handler:    _CatService_SearchCatByName_Handler,
		},
		{
			MethodName: "GetLookALikeCat",
			Handler:    _CatService_GetLookALikeCat_Handler,
		},
		{
			MethodName: "CreateCat",
			Handler:    _CatService_CreateCat_Handler,
		},
		{
			MethodName: "DeleteCat",
			Handler:    _CatService_DeleteCat_Handler,
		},
		{
			MethodName: "UpdateCat",
			Handler:    _CatService_UpdateCat_Handler,
		},
		{
			MethodName: "GetCatByID",
			Handler:    _CatService_GetCatByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mau.proto",
}
