// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: productgalery.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Productgalery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Targetid      string                 `protobuf:"bytes,2,opt,name=targetid,proto3" json:"targetid,omitempty"`
	Imageurl      string                 `protobuf:"bytes,3,opt,name=imageurl,proto3" json:"imageurl,omitempty"`
	Ismainimage   bool                   `protobuf:"varint,4,opt,name=ismainimage,proto3" json:"ismainimage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Productgalery) Reset() {
	*x = Productgalery{}
	mi := &file_productgalery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Productgalery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Productgalery) ProtoMessage() {}

func (x *Productgalery) ProtoReflect() protoreflect.Message {
	mi := &file_productgalery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Productgalery.ProtoReflect.Descriptor instead.
func (*Productgalery) Descriptor() ([]byte, []int) {
	return file_productgalery_proto_rawDescGZIP(), []int{0}
}

func (x *Productgalery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Productgalery) GetTargetid() string {
	if x != nil {
		return x.Targetid
	}
	return ""
}

func (x *Productgalery) GetImageurl() string {
	if x != nil {
		return x.Imageurl
	}
	return ""
}

func (x *Productgalery) GetIsmainimage() bool {
	if x != nil {
		return x.Ismainimage
	}
	return false
}

var File_productgalery_proto protoreflect.FileDescriptor

const file_productgalery_proto_rawDesc = "" +
	"\n" +
	"\x13productgalery.proto\x12\x03cat\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"\x9c\x01\n" +
	"\rProductgalery\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12$\n" +
	"\btargetid\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btargetid\x12)\n" +
	"\bimageurl\x18\x03 \x01(\tB\r\xbaH\n" +
	"r\b\x10\x01\x18\xf4\x03\x88\x01\x01R\bimageurl\x12 \n" +
	"\vismainimage\x18\x04 \x01(\bR\vismainimageBX\n" +
	"\acom.catB\x12ProductgaleryProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03CXX\xaa\x02\x03Cat\xca\x02\x03Cat\xe2\x02\x0fCat\\GPBMetadata\xea\x02\x03Catb\x06proto3"

var (
	file_productgalery_proto_rawDescOnce sync.Once
	file_productgalery_proto_rawDescData []byte
)

func file_productgalery_proto_rawDescGZIP() []byte {
	file_productgalery_proto_rawDescOnce.Do(func() {
		file_productgalery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_productgalery_proto_rawDesc), len(file_productgalery_proto_rawDesc)))
	})
	return file_productgalery_proto_rawDescData
}

var file_productgalery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_productgalery_proto_goTypes = []any{
	(*Productgalery)(nil), // 0: cat.Productgalery
}
var file_productgalery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_productgalery_proto_init() }
func file_productgalery_proto_init() {
	if File_productgalery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_productgalery_proto_rawDesc), len(file_productgalery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_productgalery_proto_goTypes,
		DependencyIndexes: file_productgalery_proto_depIdxs,
		MessageInfos:      file_productgalery_proto_msgTypes,
	}.Build()
	File_productgalery_proto = out.File
	file_productgalery_proto_goTypes = nil
	file_productgalery_proto_depIdxs = nil
}
