// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: driver_history.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverHistoryAction int32

const (
	DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED DriverHistoryAction = 0
	DriverHistoryAction_JOIN_ZONE                         DriverHistoryAction = 1
	DriverHistoryAction_LEAVE_ZONE                        DriverHistoryAction = 2
	DriverHistoryAction_ACCEPT_COMMAND                    DriverHistoryAction = 3
	DriverHistoryAction_SHARE_COMMAND                     DriverHistoryAction = 4
	DriverHistoryAction_DELIVER_COMMAND                   DriverHistoryAction = 5
)

// Enum value maps for DriverHistoryAction.
var (
	DriverHistoryAction_name = map[int32]string{
		0: "DRIVER_HISTORY_ACTION_UNSPECIFIED",
		1: "JOIN_ZONE",
		2: "LEAVE_ZONE",
		3: "ACCEPT_COMMAND",
		4: "SHARE_COMMAND",
		5: "DELIVER_COMMAND",
	}
	DriverHistoryAction_value = map[string]int32{
		"DRIVER_HISTORY_ACTION_UNSPECIFIED": 0,
		"JOIN_ZONE":                         1,
		"LEAVE_ZONE":                        2,
		"ACCEPT_COMMAND":                    3,
		"SHARE_COMMAND":                     4,
		"DELIVER_COMMAND":                   5,
	}
)

func (x DriverHistoryAction) Enum() *DriverHistoryAction {
	p := new(DriverHistoryAction)
	*p = x
	return p
}

func (x DriverHistoryAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverHistoryAction) Descriptor() protoreflect.EnumDescriptor {
	return file_driver_history_proto_enumTypes[0].Descriptor()
}

func (DriverHistoryAction) Type() protoreflect.EnumType {
	return &file_driver_history_proto_enumTypes[0]
}

func (x DriverHistoryAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverHistoryAction.Descriptor instead.
func (DriverHistoryAction) EnumDescriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{0}
}

type DriverHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        DriverHistoryAction    `protobuf:"varint,2,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CommandFee    float64                `protobuf:"fixed64,5,opt,name=command_fee,json=commandFee,proto3" json:"command_fee,omitempty"`
	ZoneId        string                 `protobuf:"bytes,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverHistory) Reset() {
	*x = DriverHistory{}
	mi := &file_driver_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverHistory) ProtoMessage() {}

func (x *DriverHistory) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverHistory.ProtoReflect.Descriptor instead.
func (*DriverHistory) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{0}
}

func (x *DriverHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverHistory) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *DriverHistory) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DriverHistory) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverHistory) GetCommandFee() float64 {
	if x != nil {
		return x.CommandFee
	}
	return 0
}

func (x *DriverHistory) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *DriverHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DriverHistory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DriverHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverHistory *DriverHistory         `protobuf:"bytes,1,opt,name=driver_history,json=driverHistory,proto3" json:"driver_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverHistoryResponse) Reset() {
	*x = DriverHistoryResponse{}
	mi := &file_driver_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverHistoryResponse) ProtoMessage() {}

func (x *DriverHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverHistoryResponse.ProtoReflect.Descriptor instead.
func (*DriverHistoryResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{1}
}

func (x *DriverHistoryResponse) GetDriverHistory() *DriverHistory {
	if x != nil {
		return x.DriverHistory
	}
	return nil
}

type DriverHistoryListResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DriverHistories []*DriverHistory       `protobuf:"bytes,1,rep,name=driver_histories,json=driverHistories,proto3" json:"driver_histories,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriverHistoryListResponse) Reset() {
	*x = DriverHistoryListResponse{}
	mi := &file_driver_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverHistoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverHistoryListResponse) ProtoMessage() {}

func (x *DriverHistoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverHistoryListResponse.ProtoReflect.Descriptor instead.
func (*DriverHistoryListResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{2}
}

func (x *DriverHistoryListResponse) GetDriverHistories() []*DriverHistory {
	if x != nil {
		return x.DriverHistories
	}
	return nil
}

type CreateDriverHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        DriverHistoryAction    `protobuf:"varint,1,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CommandFee    float64                `protobuf:"fixed64,4,opt,name=command_fee,json=commandFee,proto3" json:"command_fee,omitempty"`
	ZoneId        string                 `protobuf:"bytes,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverHistoryRequest) Reset() {
	*x = CreateDriverHistoryRequest{}
	mi := &file_driver_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverHistoryRequest) ProtoMessage() {}

func (x *CreateDriverHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverHistoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverHistoryRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDriverHistoryRequest) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *CreateDriverHistoryRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CreateDriverHistoryRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateDriverHistoryRequest) GetCommandFee() float64 {
	if x != nil {
		return x.CommandFee
	}
	return 0
}

func (x *CreateDriverHistoryRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type GetDriverHistoryByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverHistoryByIDRequest) Reset() {
	*x = GetDriverHistoryByIDRequest{}
	mi := &file_driver_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverHistoryByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverHistoryByIDRequest) ProtoMessage() {}

func (x *GetDriverHistoryByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverHistoryByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDriverHistoryByIDRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetDriverHistoryByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadAllDriverHistoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllDriverHistoriesRequest) Reset() {
	*x = ReadAllDriverHistoriesRequest{}
	mi := &file_driver_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllDriverHistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllDriverHistoriesRequest) ProtoMessage() {}

func (x *ReadAllDriverHistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllDriverHistoriesRequest.ProtoReflect.Descriptor instead.
func (*ReadAllDriverHistoriesRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllDriverHistoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadAllDriverHistoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateDriverHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        DriverHistoryAction    `protobuf:"varint,2,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CommandFee    float64                `protobuf:"fixed64,5,opt,name=command_fee,json=commandFee,proto3" json:"command_fee,omitempty"`
	ZoneId        string                 `protobuf:"bytes,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverHistoryRequest) Reset() {
	*x = UpdateDriverHistoryRequest{}
	mi := &file_driver_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverHistoryRequest) ProtoMessage() {}

func (x *UpdateDriverHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverHistoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverHistoryRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDriverHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDriverHistoryRequest) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *UpdateDriverHistoryRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *UpdateDriverHistoryRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverHistoryRequest) GetCommandFee() float64 {
	if x != nil {
		return x.CommandFee
	}
	return 0
}

func (x *UpdateDriverHistoryRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type DeleteDriverHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverHistoryRequest) Reset() {
	*x = DeleteDriverHistoryRequest{}
	mi := &file_driver_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverHistoryRequest) ProtoMessage() {}

func (x *DeleteDriverHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverHistoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDriverHistoryRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDriverHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDriverHistoriesByDriverIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverHistoriesByDriverIDRequest) Reset() {
	*x = GetDriverHistoriesByDriverIDRequest{}
	mi := &file_driver_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverHistoriesByDriverIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverHistoriesByDriverIDRequest) ProtoMessage() {}

func (x *GetDriverHistoriesByDriverIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverHistoriesByDriverIDRequest.ProtoReflect.Descriptor instead.
func (*GetDriverHistoriesByDriverIDRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{8}
}

func (x *GetDriverHistoriesByDriverIDRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverHistoriesByDriverIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDriverHistoriesByDriverIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDriverHistoriesByActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        DriverHistoryAction    `protobuf:"varint,1,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverHistoriesByActionRequest) Reset() {
	*x = GetDriverHistoriesByActionRequest{}
	mi := &file_driver_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverHistoriesByActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverHistoriesByActionRequest) ProtoMessage() {}

func (x *GetDriverHistoriesByActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverHistoriesByActionRequest.ProtoReflect.Descriptor instead.
func (*GetDriverHistoriesByActionRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{9}
}

func (x *GetDriverHistoriesByActionRequest) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *GetDriverHistoriesByActionRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDriverHistoriesByActionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDriverHistoriesByDriverIDAndActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        DriverHistoryAction    `protobuf:"varint,2,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverHistoriesByDriverIDAndActionRequest) Reset() {
	*x = GetDriverHistoriesByDriverIDAndActionRequest{}
	mi := &file_driver_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverHistoriesByDriverIDAndActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverHistoriesByDriverIDAndActionRequest) ProtoMessage() {}

func (x *GetDriverHistoriesByDriverIDAndActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverHistoriesByDriverIDAndActionRequest.ProtoReflect.Descriptor instead.
func (*GetDriverHistoriesByDriverIDAndActionRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{10}
}

func (x *GetDriverHistoriesByDriverIDAndActionRequest) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *GetDriverHistoriesByDriverIDAndActionRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDriverHistoriesByDriverIDAndActionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDriverHistoriesByDriverIDBetweenDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverHistoriesByDriverIDBetweenDatesRequest) Reset() {
	*x = GetDriverHistoriesByDriverIDBetweenDatesRequest{}
	mi := &file_driver_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverHistoriesByDriverIDBetweenDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverHistoriesByDriverIDBetweenDatesRequest) ProtoMessage() {}

func (x *GetDriverHistoriesByDriverIDBetweenDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverHistoriesByDriverIDBetweenDatesRequest.ProtoReflect.Descriptor instead.
func (*GetDriverHistoriesByDriverIDBetweenDatesRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriverHistoriesByDriverIDBetweenDatesRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverHistoriesByDriverIDBetweenDatesRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDriverHistoriesByDriverIDBetweenDatesRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetDriverHistoriesByActionBetweenDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        DriverHistoryAction    `protobuf:"varint,1,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverHistoriesByActionBetweenDatesRequest) Reset() {
	*x = GetDriverHistoriesByActionBetweenDatesRequest{}
	mi := &file_driver_history_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverHistoriesByActionBetweenDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverHistoriesByActionBetweenDatesRequest) ProtoMessage() {}

func (x *GetDriverHistoriesByActionBetweenDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverHistoriesByActionBetweenDatesRequest.ProtoReflect.Descriptor instead.
func (*GetDriverHistoriesByActionBetweenDatesRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{12}
}

func (x *GetDriverHistoriesByActionBetweenDatesRequest) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *GetDriverHistoriesByActionBetweenDatesRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDriverHistoriesByActionBetweenDatesRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type CountAcceptedCommandsByDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountAcceptedCommandsByDayRequest) Reset() {
	*x = CountAcceptedCommandsByDayRequest{}
	mi := &file_driver_history_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountAcceptedCommandsByDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountAcceptedCommandsByDayRequest) ProtoMessage() {}

func (x *CountAcceptedCommandsByDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountAcceptedCommandsByDayRequest.ProtoReflect.Descriptor instead.
func (*CountAcceptedCommandsByDayRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{13}
}

func (x *CountAcceptedCommandsByDayRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CountAcceptedCommandsByDayRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type CountAcceptedCommandsByDayForAllDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountAcceptedCommandsByDayForAllDriversRequest) Reset() {
	*x = CountAcceptedCommandsByDayForAllDriversRequest{}
	mi := &file_driver_history_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountAcceptedCommandsByDayForAllDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountAcceptedCommandsByDayForAllDriversRequest) ProtoMessage() {}

func (x *CountAcceptedCommandsByDayForAllDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountAcceptedCommandsByDayForAllDriversRequest.ProtoReflect.Descriptor instead.
func (*CountAcceptedCommandsByDayForAllDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{14}
}

func (x *CountAcceptedCommandsByDayForAllDriversRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CountAcceptedCommandsByDayForAllDriversRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type CommandCountByDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandCountByDay) Reset() {
	*x = CommandCountByDay{}
	mi := &file_driver_history_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandCountByDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandCountByDay) ProtoMessage() {}

func (x *CommandCountByDay) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandCountByDay.ProtoReflect.Descriptor instead.
func (*CommandCountByDay) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{15}
}

func (x *CommandCountByDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CommandCountByDay) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CommandCountByDayListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CommandCountByDay   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandCountByDayListResponse) Reset() {
	*x = CommandCountByDayListResponse{}
	mi := &file_driver_history_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandCountByDayListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandCountByDayListResponse) ProtoMessage() {}

func (x *CommandCountByDayListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandCountByDayListResponse.ProtoReflect.Descriptor instead.
func (*CommandCountByDayListResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{16}
}

func (x *CommandCountByDayListResponse) GetItems() []*CommandCountByDay {
	if x != nil {
		return x.Items
	}
	return nil
}

type CountActionsByDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountActionsByDriverRequest) Reset() {
	*x = CountActionsByDriverRequest{}
	mi := &file_driver_history_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountActionsByDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountActionsByDriverRequest) ProtoMessage() {}

func (x *CountActionsByDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountActionsByDriverRequest.ProtoReflect.Descriptor instead.
func (*CountActionsByDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{17}
}

func (x *CountActionsByDriverRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CountActionsByDriverRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ActionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        DriverHistoryAction    `protobuf:"varint,1,opt,name=action,proto3,enum=driver_history.DriverHistoryAction" json:"action,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCount) Reset() {
	*x = ActionCount{}
	mi := &file_driver_history_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCount) ProtoMessage() {}

func (x *ActionCount) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCount.ProtoReflect.Descriptor instead.
func (*ActionCount) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{18}
}

func (x *ActionCount) GetAction() DriverHistoryAction {
	if x != nil {
		return x.Action
	}
	return DriverHistoryAction_DRIVER_HISTORY_ACTION_UNSPECIFIED
}

func (x *ActionCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ActionCountListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ActionCount         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCountListResponse) Reset() {
	*x = ActionCountListResponse{}
	mi := &file_driver_history_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCountListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCountListResponse) ProtoMessage() {}

func (x *ActionCountListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCountListResponse.ProtoReflect.Descriptor instead.
func (*ActionCountListResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{19}
}

func (x *ActionCountListResponse) GetItems() []*ActionCount {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetWorkedHoursByDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkedHoursByDayRequest) Reset() {
	*x = GetWorkedHoursByDayRequest{}
	mi := &file_driver_history_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkedHoursByDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkedHoursByDayRequest) ProtoMessage() {}

func (x *GetWorkedHoursByDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkedHoursByDayRequest.ProtoReflect.Descriptor instead.
func (*GetWorkedHoursByDayRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{20}
}

func (x *GetWorkedHoursByDayRequest) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

type GetWorkedHoursBetweenDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkedHoursBetweenDatesRequest) Reset() {
	*x = GetWorkedHoursBetweenDatesRequest{}
	mi := &file_driver_history_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkedHoursBetweenDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkedHoursBetweenDatesRequest) ProtoMessage() {}

func (x *GetWorkedHoursBetweenDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkedHoursBetweenDatesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkedHoursBetweenDatesRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{21}
}

func (x *GetWorkedHoursBetweenDatesRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetWorkedHoursBetweenDatesRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type WorkedHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Hours         float64                `protobuf:"fixed64,3,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       int32                  `protobuf:"varint,4,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkedHours) Reset() {
	*x = WorkedHours{}
	mi := &file_driver_history_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkedHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkedHours) ProtoMessage() {}

func (x *WorkedHours) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkedHours.ProtoReflect.Descriptor instead.
func (*WorkedHours) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{22}
}

func (x *WorkedHours) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *WorkedHours) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WorkedHours) GetHours() float64 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *WorkedHours) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type WorkedHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkedHours   *WorkedHours           `protobuf:"bytes,1,opt,name=worked_hours,json=workedHours,proto3" json:"worked_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkedHoursResponse) Reset() {
	*x = WorkedHoursResponse{}
	mi := &file_driver_history_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkedHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkedHoursResponse) ProtoMessage() {}

func (x *WorkedHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkedHoursResponse.ProtoReflect.Descriptor instead.
func (*WorkedHoursResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{23}
}

func (x *WorkedHoursResponse) GetWorkedHours() *WorkedHours {
	if x != nil {
		return x.WorkedHours
	}
	return nil
}

type WorkedHoursListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WorkedHours         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkedHoursListResponse) Reset() {
	*x = WorkedHoursListResponse{}
	mi := &file_driver_history_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkedHoursListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkedHoursListResponse) ProtoMessage() {}

func (x *WorkedHoursListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkedHoursListResponse.ProtoReflect.Descriptor instead.
func (*WorkedHoursListResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{24}
}

func (x *WorkedHoursListResponse) GetItems() []*WorkedHours {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetTotalCommandFeesByDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalCommandFeesByDayRequest) Reset() {
	*x = GetTotalCommandFeesByDayRequest{}
	mi := &file_driver_history_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalCommandFeesByDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalCommandFeesByDayRequest) ProtoMessage() {}

func (x *GetTotalCommandFeesByDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalCommandFeesByDayRequest.ProtoReflect.Descriptor instead.
func (*GetTotalCommandFeesByDayRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{25}
}

func (x *GetTotalCommandFeesByDayRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTotalCommandFeesByDayRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type FeeByDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeByDay) Reset() {
	*x = FeeByDay{}
	mi := &file_driver_history_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeByDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeByDay) ProtoMessage() {}

func (x *FeeByDay) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeByDay.ProtoReflect.Descriptor instead.
func (*FeeByDay) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{26}
}

func (x *FeeByDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FeeByDay) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FeeByDayListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeeByDay            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeByDayListResponse) Reset() {
	*x = FeeByDayListResponse{}
	mi := &file_driver_history_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeByDayListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeByDayListResponse) ProtoMessage() {}

func (x *FeeByDayListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeByDayListResponse.ProtoReflect.Descriptor instead.
func (*FeeByDayListResponse) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{27}
}

func (x *FeeByDayListResponse) GetItems() []*FeeByDay {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrackJoinZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackJoinZoneRequest) Reset() {
	*x = TrackJoinZoneRequest{}
	mi := &file_driver_history_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackJoinZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackJoinZoneRequest) ProtoMessage() {}

func (x *TrackJoinZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackJoinZoneRequest.ProtoReflect.Descriptor instead.
func (*TrackJoinZoneRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{28}
}

func (x *TrackJoinZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type TrackLeaveZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackLeaveZoneRequest) Reset() {
	*x = TrackLeaveZoneRequest{}
	mi := &file_driver_history_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackLeaveZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLeaveZoneRequest) ProtoMessage() {}

func (x *TrackLeaveZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLeaveZoneRequest.ProtoReflect.Descriptor instead.
func (*TrackLeaveZoneRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{29}
}

func (x *TrackLeaveZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type TrackAcceptCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandFee    float64                `protobuf:"fixed64,3,opt,name=command_fee,json=commandFee,proto3" json:"command_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackAcceptCommandRequest) Reset() {
	*x = TrackAcceptCommandRequest{}
	mi := &file_driver_history_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackAcceptCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackAcceptCommandRequest) ProtoMessage() {}

func (x *TrackAcceptCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackAcceptCommandRequest.ProtoReflect.Descriptor instead.
func (*TrackAcceptCommandRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{30}
}

func (x *TrackAcceptCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TrackAcceptCommandRequest) GetCommandFee() float64 {
	if x != nil {
		return x.CommandFee
	}
	return 0
}

type TrackShareCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandFee    float64                `protobuf:"fixed64,3,opt,name=command_fee,json=commandFee,proto3" json:"command_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackShareCommandRequest) Reset() {
	*x = TrackShareCommandRequest{}
	mi := &file_driver_history_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShareCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShareCommandRequest) ProtoMessage() {}

func (x *TrackShareCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShareCommandRequest.ProtoReflect.Descriptor instead.
func (*TrackShareCommandRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{31}
}

func (x *TrackShareCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TrackShareCommandRequest) GetCommandFee() float64 {
	if x != nil {
		return x.CommandFee
	}
	return 0
}

type TrackDeliverCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandFee    float64                `protobuf:"fixed64,3,opt,name=command_fee,json=commandFee,proto3" json:"command_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackDeliverCommandRequest) Reset() {
	*x = TrackDeliverCommandRequest{}
	mi := &file_driver_history_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackDeliverCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackDeliverCommandRequest) ProtoMessage() {}

func (x *TrackDeliverCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_history_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackDeliverCommandRequest.ProtoReflect.Descriptor instead.
func (*TrackDeliverCommandRequest) Descriptor() ([]byte, []int) {
	return file_driver_history_proto_rawDescGZIP(), []int{32}
}

func (x *TrackDeliverCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TrackDeliverCommandRequest) GetCommandFee() float64 {
	if x != nil {
		return x.CommandFee
	}
	return 0
}

var File_driver_history_proto protoreflect.FileDescriptor

const file_driver_history_proto_rawDesc = "" +
	"\n" +
	"\x14driver_history.proto\x12\x0edriver_history\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\xc8\x02\n" +
	"\rDriverHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x06action\x18\x02 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vcommand_fee\x18\x05 \x01(\x01R\n" +
	"commandFee\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\tR\x06zoneId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"]\n" +
	"\x15DriverHistoryResponse\x12D\n" +
	"\x0edriver_history\x18\x01 \x01(\v2\x1d.driver_history.DriverHistoryR\rdriverHistory\"e\n" +
	"\x19DriverHistoryListResponse\x12H\n" +
	"\x10driver_histories\x18\x01 \x03(\v2\x1d.driver_history.DriverHistoryR\x0fdriverHistories\"\xcf\x01\n" +
	"\x1aCreateDriverHistoryRequest\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vcommand_fee\x18\x04 \x01(\x01R\n" +
	"commandFee\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\tR\x06zoneId\"-\n" +
	"\x1bGetDriverHistoryByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x1dReadAllDriverHistoriesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xdf\x01\n" +
	"\x1aUpdateDriverHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x06action\x18\x02 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vcommand_fee\x18\x05 \x01(\x01R\n" +
	"commandFee\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\tR\x06zoneId\",\n" +
	"\x1aDeleteDriverHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"#GetDriverHistoriesByDriverIDRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8e\x01\n" +
	"!GetDriverHistoriesByActionRequest\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x99\x01\n" +
	",GetDriverHistoriesByDriverIDAndActionRequest\x12;\n" +
	"\x06action\x18\x02 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc0\x01\n" +
	"/GetDriverHistoriesByDriverIDBetweenDatesRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xde\x01\n" +
	"-GetDriverHistoriesByActionBetweenDatesRequest\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x95\x01\n" +
	"!CountAcceptedCommandsByDayRequest\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xa2\x01\n" +
	".CountAcceptedCommandsByDayForAllDriversRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"=\n" +
	"\x11CommandCountByDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"X\n" +
	"\x1dCommandCountByDayListResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.driver_history.CommandCountByDayR\x05items\"\x8f\x01\n" +
	"\x1bCountActionsByDriverRequest\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"`\n" +
	"\vActionCount\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.driver_history.DriverHistoryActionR\x06action\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"L\n" +
	"\x17ActionCountListResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.driver_history.ActionCountR\x05items\"J\n" +
	"\x1aGetWorkedHoursByDayRequest\x12,\n" +
	"\x03day\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\"\x95\x01\n" +
	"!GetWorkedHoursBetweenDatesRequest\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"n\n" +
	"\vWorkedHours\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x14\n" +
	"\x05hours\x18\x03 \x01(\x01R\x05hours\x12\x18\n" +
	"\aminutes\x18\x04 \x01(\x05R\aminutes\"U\n" +
	"\x13WorkedHoursResponse\x12>\n" +
	"\fworked_hours\x18\x01 \x01(\v2\x1b.driver_history.WorkedHoursR\vworkedHours\"L\n" +
	"\x17WorkedHoursListResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.driver_history.WorkedHoursR\x05items\"\x93\x01\n" +
	"\x1fGetTotalCommandFeesByDayRequest\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"4\n" +
	"\bFeeByDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"F\n" +
	"\x14FeeByDayListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.driver_history.FeeByDayR\x05items\"/\n" +
	"\x14TrackJoinZoneRequest\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\"0\n" +
	"\x15TrackLeaveZoneRequest\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\"[\n" +
	"\x19TrackAcceptCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vcommand_fee\x18\x03 \x01(\x01R\n" +
	"commandFee\"Z\n" +
	"\x18TrackShareCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vcommand_fee\x18\x03 \x01(\x01R\n" +
	"commandFee\"\\\n" +
	"\x1aTrackDeliverCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vcommand_fee\x18\x03 \x01(\x01R\n" +
	"commandFee*\x97\x01\n" +
	"\x13DriverHistoryAction\x12%\n" +
	"!DRIVER_HISTORY_ACTION_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tJOIN_ZONE\x10\x01\x12\x0e\n" +
	"\n" +
	"LEAVE_ZONE\x10\x02\x12\x12\n" +
	"\x0eACCEPT_COMMAND\x10\x03\x12\x11\n" +
	"\rSHARE_COMMAND\x10\x04\x12\x13\n" +
	"\x0fDELIVER_COMMAND\x10\x052\x87\x1c\n" +
	"\x14DriverHistoryService\x12\x91\x01\n" +
	"\x13CreateDriverHistory\x12*.driver_history.CreateDriverHistoryRequest\x1a%.driver_history.DriverHistoryResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/abyssin/driver-histories\x12\x95\x01\n" +
	"\x14GetDriverHistoryByID\x12+.driver_history.GetDriverHistoryByIDRequest\x1a%.driver_history.DriverHistoryResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/abyssin/driver-histories/{id}\x12\x98\x01\n" +
	"\x16ReadAllDriverHistories\x12-.driver_history.ReadAllDriverHistoriesRequest\x1a).driver_history.DriverHistoryListResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/abyssin/driver-histories\x12\x96\x01\n" +
	"\x13UpdateDriverHistory\x12*.driver_history.UpdateDriverHistoryRequest\x1a%.driver_history.DriverHistoryResponse\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/v1/abyssin/driver-histories/{id}\x12\x84\x01\n" +
	"\x13DeleteDriverHistory\x12*.driver_history.DeleteDriverHistoryRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#*!/v1/abyssin/driver-histories/{id}\x12\xa5\x01\n" +
	"\x1cGetDriverHistoriesByDriverID\x123.driver_history.GetDriverHistoriesByDriverIDRequest\x1a).driver_history.DriverHistoryListResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/abyssin/drivers/histories\x12\xb1\x01\n" +
	"\x1aGetDriverHistoriesByAction\x121.driver_history.GetDriverHistoriesByActionRequest\x1a).driver_history.DriverHistoryListResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/abyssin/driver-histories/actions/{action}\x12\xc8\x01\n" +
	"%GetDriverHistoriesByDriverIDAndAction\x12<.driver_history.GetDriverHistoriesByDriverIDAndActionRequest\x1a).driver_history.DriverHistoryListResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/abyssin/drivers/histories/actions/{action}\x12\xc8\x01\n" +
	"(GetDriverHistoriesByDriverIDBetweenDates\x12?.driver_history.GetDriverHistoriesByDriverIDBetweenDatesRequest\x1a).driver_history.DriverHistoryListResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/abyssin/drivers/histories/date-range\x12\xd4\x01\n" +
	"&GetDriverHistoriesByActionBetweenDates\x12=.driver_history.GetDriverHistoriesByActionBetweenDatesRequest\x1a).driver_history.DriverHistoryListResponse\"@\x82\xd3\xe4\x93\x02:\x128/v1/abyssin/driver-histories/actions/{action}/date-range\x12\xba\x01\n" +
	"\x1aCountAcceptedCommandsByDay\x121.driver_history.CountAcceptedCommandsByDayRequest\x1a-.driver_history.CommandCountByDayListResponse\":\x82\xd3\xe4\x93\x024\x122/v1/abyssin/drivers/stats/accepted-commands-by-day\x12\xcc\x01\n" +
	"'CountAcceptedCommandsByDayForAllDrivers\x12>.driver_history.CountAcceptedCommandsByDayForAllDriversRequest\x1a-.driver_history.CommandCountByDayListResponse\"2\x82\xd3\xe4\x93\x02,\x12*/v1/abyssin/stats/accepted-commands-by-day\x12\x97\x01\n" +
	"\x14CountActionsByDriver\x12+.driver_history.CountActionsByDriverRequest\x1a'.driver_history.ActionCountListResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/abyssin/drivers/stats/actions\x12\x9a\x01\n" +
	"\x13GetWorkedHoursByDay\x12*.driver_history.GetWorkedHoursByDayRequest\x1a#.driver_history.WorkedHoursResponse\"2\x82\xd3\xe4\x93\x02,\x12*/v1/abyssin/drivers/stats/worked-hours/day\x12\xb3\x01\n" +
	"\x1aGetWorkedHoursBetweenDates\x121.driver_history.GetWorkedHoursBetweenDatesRequest\x1a'.driver_history.WorkedHoursListResponse\"9\x82\xd3\xe4\x93\x023\x121/v1/abyssin/drivers/stats/worked-hours/date-range\x12\xa8\x01\n" +
	"\x18GetTotalCommandFeesByDay\x12/.driver_history.GetTotalCommandFeesByDayRequest\x1a$.driver_history.FeeByDayListResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/abyssin/drivers/stats/command-fees-by-day\x12\x91\x01\n" +
	"\rTrackJoinZone\x12$.driver_history.TrackJoinZoneRequest\x1a%.driver_history.DriverHistoryResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/abyssin/drivers/zones/{zone_id}/join\x12\x94\x01\n" +
	"\x0eTrackLeaveZone\x12%.driver_history.TrackLeaveZoneRequest\x1a%.driver_history.DriverHistoryResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/v1/abyssin/drivers/zones/{zone_id}/leave\x12\xa3\x01\n" +
	"\x12TrackAcceptCommand\x12).driver_history.TrackAcceptCommandRequest\x1a%.driver_history.DriverHistoryResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/abyssin/drivers/commands/{command_id}/accept\x12\xa0\x01\n" +
	"\x11TrackShareCommand\x12(.driver_history.TrackShareCommandRequest\x1a%.driver_history.DriverHistoryResponse\":\x82\xd3\xe4\x93\x024:\x01*\"//v1/abyssin/drivers/commands/{command_id}/share\x12\xa6\x01\n" +
	"\x13TrackDeliverCommand\x12*.driver_history.TrackDeliverCommandRequest\x1a%.driver_history.DriverHistoryResponse\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/abyssin/drivers/commands/{command_id}/deliverB\x8b\x01\n" +
	"\x12com.driver_historyB\x12DriverHistoryProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03DXX\xaa\x02\rDriverHistory\xca\x02\rDriverHistory\xe2\x02\x19DriverHistory\\GPBMetadata\xea\x02\rDriverHistoryb\x06proto3"

var (
	file_driver_history_proto_rawDescOnce sync.Once
	file_driver_history_proto_rawDescData []byte
)

func file_driver_history_proto_rawDescGZIP() []byte {
	file_driver_history_proto_rawDescOnce.Do(func() {
		file_driver_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_history_proto_rawDesc), len(file_driver_history_proto_rawDesc)))
	})
	return file_driver_history_proto_rawDescData
}

var file_driver_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_driver_history_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_driver_history_proto_goTypes = []any{
	(DriverHistoryAction)(0),                                // 0: driver_history.DriverHistoryAction
	(*DriverHistory)(nil),                                   // 1: driver_history.DriverHistory
	(*DriverHistoryResponse)(nil),                           // 2: driver_history.DriverHistoryResponse
	(*DriverHistoryListResponse)(nil),                       // 3: driver_history.DriverHistoryListResponse
	(*CreateDriverHistoryRequest)(nil),                      // 4: driver_history.CreateDriverHistoryRequest
	(*GetDriverHistoryByIDRequest)(nil),                     // 5: driver_history.GetDriverHistoryByIDRequest
	(*ReadAllDriverHistoriesRequest)(nil),                   // 6: driver_history.ReadAllDriverHistoriesRequest
	(*UpdateDriverHistoryRequest)(nil),                      // 7: driver_history.UpdateDriverHistoryRequest
	(*DeleteDriverHistoryRequest)(nil),                      // 8: driver_history.DeleteDriverHistoryRequest
	(*GetDriverHistoriesByDriverIDRequest)(nil),             // 9: driver_history.GetDriverHistoriesByDriverIDRequest
	(*GetDriverHistoriesByActionRequest)(nil),               // 10: driver_history.GetDriverHistoriesByActionRequest
	(*GetDriverHistoriesByDriverIDAndActionRequest)(nil),    // 11: driver_history.GetDriverHistoriesByDriverIDAndActionRequest
	(*GetDriverHistoriesByDriverIDBetweenDatesRequest)(nil), // 12: driver_history.GetDriverHistoriesByDriverIDBetweenDatesRequest
	(*GetDriverHistoriesByActionBetweenDatesRequest)(nil),   // 13: driver_history.GetDriverHistoriesByActionBetweenDatesRequest
	(*CountAcceptedCommandsByDayRequest)(nil),               // 14: driver_history.CountAcceptedCommandsByDayRequest
	(*CountAcceptedCommandsByDayForAllDriversRequest)(nil),  // 15: driver_history.CountAcceptedCommandsByDayForAllDriversRequest
	(*CommandCountByDay)(nil),                               // 16: driver_history.CommandCountByDay
	(*CommandCountByDayListResponse)(nil),                   // 17: driver_history.CommandCountByDayListResponse
	(*CountActionsByDriverRequest)(nil),                     // 18: driver_history.CountActionsByDriverRequest
	(*ActionCount)(nil),                                     // 19: driver_history.ActionCount
	(*ActionCountListResponse)(nil),                         // 20: driver_history.ActionCountListResponse
	(*GetWorkedHoursByDayRequest)(nil),                      // 21: driver_history.GetWorkedHoursByDayRequest
	(*GetWorkedHoursBetweenDatesRequest)(nil),               // 22: driver_history.GetWorkedHoursBetweenDatesRequest
	(*WorkedHours)(nil),                                     // 23: driver_history.WorkedHours
	(*WorkedHoursResponse)(nil),                             // 24: driver_history.WorkedHoursResponse
	(*WorkedHoursListResponse)(nil),                         // 25: driver_history.WorkedHoursListResponse
	(*GetTotalCommandFeesByDayRequest)(nil),                 // 26: driver_history.GetTotalCommandFeesByDayRequest
	(*FeeByDay)(nil),                                        // 27: driver_history.FeeByDay
	(*FeeByDayListResponse)(nil),                            // 28: driver_history.FeeByDayListResponse
	(*TrackJoinZoneRequest)(nil),                            // 29: driver_history.TrackJoinZoneRequest
	(*TrackLeaveZoneRequest)(nil),                           // 30: driver_history.TrackLeaveZoneRequest
	(*TrackAcceptCommandRequest)(nil),                       // 31: driver_history.TrackAcceptCommandRequest
	(*TrackShareCommandRequest)(nil),                        // 32: driver_history.TrackShareCommandRequest
	(*TrackDeliverCommandRequest)(nil),                      // 33: driver_history.TrackDeliverCommandRequest
	(*timestamppb.Timestamp)(nil),                           // 34: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                                   // 35: google.protobuf.Empty
}
var file_driver_history_proto_depIdxs = []int32{
	0,  // 0: driver_history.DriverHistory.action:type_name -> driver_history.DriverHistoryAction
	34, // 1: driver_history.DriverHistory.created_at:type_name -> google.protobuf.Timestamp
	34, // 2: driver_history.DriverHistory.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: driver_history.DriverHistoryResponse.driver_history:type_name -> driver_history.DriverHistory
	1,  // 4: driver_history.DriverHistoryListResponse.driver_histories:type_name -> driver_history.DriverHistory
	0,  // 5: driver_history.CreateDriverHistoryRequest.action:type_name -> driver_history.DriverHistoryAction
	0,  // 6: driver_history.UpdateDriverHistoryRequest.action:type_name -> driver_history.DriverHistoryAction
	0,  // 7: driver_history.GetDriverHistoriesByActionRequest.action:type_name -> driver_history.DriverHistoryAction
	0,  // 8: driver_history.GetDriverHistoriesByDriverIDAndActionRequest.action:type_name -> driver_history.DriverHistoryAction
	34, // 9: driver_history.GetDriverHistoriesByDriverIDBetweenDatesRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 10: driver_history.GetDriverHistoriesByDriverIDBetweenDatesRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 11: driver_history.GetDriverHistoriesByActionBetweenDatesRequest.action:type_name -> driver_history.DriverHistoryAction
	34, // 12: driver_history.GetDriverHistoriesByActionBetweenDatesRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 13: driver_history.GetDriverHistoriesByActionBetweenDatesRequest.end_date:type_name -> google.protobuf.Timestamp
	34, // 14: driver_history.CountAcceptedCommandsByDayRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 15: driver_history.CountAcceptedCommandsByDayRequest.end_date:type_name -> google.protobuf.Timestamp
	34, // 16: driver_history.CountAcceptedCommandsByDayForAllDriversRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 17: driver_history.CountAcceptedCommandsByDayForAllDriversRequest.end_date:type_name -> google.protobuf.Timestamp
	16, // 18: driver_history.CommandCountByDayListResponse.items:type_name -> driver_history.CommandCountByDay
	34, // 19: driver_history.CountActionsByDriverRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 20: driver_history.CountActionsByDriverRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 21: driver_history.ActionCount.action:type_name -> driver_history.DriverHistoryAction
	19, // 22: driver_history.ActionCountListResponse.items:type_name -> driver_history.ActionCount
	34, // 23: driver_history.GetWorkedHoursByDayRequest.day:type_name -> google.protobuf.Timestamp
	34, // 24: driver_history.GetWorkedHoursBetweenDatesRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 25: driver_history.GetWorkedHoursBetweenDatesRequest.end_date:type_name -> google.protobuf.Timestamp
	23, // 26: driver_history.WorkedHoursResponse.worked_hours:type_name -> driver_history.WorkedHours
	23, // 27: driver_history.WorkedHoursListResponse.items:type_name -> driver_history.WorkedHours
	34, // 28: driver_history.GetTotalCommandFeesByDayRequest.start_date:type_name -> google.protobuf.Timestamp
	34, // 29: driver_history.GetTotalCommandFeesByDayRequest.end_date:type_name -> google.protobuf.Timestamp
	27, // 30: driver_history.FeeByDayListResponse.items:type_name -> driver_history.FeeByDay
	4,  // 31: driver_history.DriverHistoryService.CreateDriverHistory:input_type -> driver_history.CreateDriverHistoryRequest
	5,  // 32: driver_history.DriverHistoryService.GetDriverHistoryByID:input_type -> driver_history.GetDriverHistoryByIDRequest
	6,  // 33: driver_history.DriverHistoryService.ReadAllDriverHistories:input_type -> driver_history.ReadAllDriverHistoriesRequest
	7,  // 34: driver_history.DriverHistoryService.UpdateDriverHistory:input_type -> driver_history.UpdateDriverHistoryRequest
	8,  // 35: driver_history.DriverHistoryService.DeleteDriverHistory:input_type -> driver_history.DeleteDriverHistoryRequest
	9,  // 36: driver_history.DriverHistoryService.GetDriverHistoriesByDriverID:input_type -> driver_history.GetDriverHistoriesByDriverIDRequest
	10, // 37: driver_history.DriverHistoryService.GetDriverHistoriesByAction:input_type -> driver_history.GetDriverHistoriesByActionRequest
	11, // 38: driver_history.DriverHistoryService.GetDriverHistoriesByDriverIDAndAction:input_type -> driver_history.GetDriverHistoriesByDriverIDAndActionRequest
	12, // 39: driver_history.DriverHistoryService.GetDriverHistoriesByDriverIDBetweenDates:input_type -> driver_history.GetDriverHistoriesByDriverIDBetweenDatesRequest
	13, // 40: driver_history.DriverHistoryService.GetDriverHistoriesByActionBetweenDates:input_type -> driver_history.GetDriverHistoriesByActionBetweenDatesRequest
	14, // 41: driver_history.DriverHistoryService.CountAcceptedCommandsByDay:input_type -> driver_history.CountAcceptedCommandsByDayRequest
	15, // 42: driver_history.DriverHistoryService.CountAcceptedCommandsByDayForAllDrivers:input_type -> driver_history.CountAcceptedCommandsByDayForAllDriversRequest
	18, // 43: driver_history.DriverHistoryService.CountActionsByDriver:input_type -> driver_history.CountActionsByDriverRequest
	21, // 44: driver_history.DriverHistoryService.GetWorkedHoursByDay:input_type -> driver_history.GetWorkedHoursByDayRequest
	22, // 45: driver_history.DriverHistoryService.GetWorkedHoursBetweenDates:input_type -> driver_history.GetWorkedHoursBetweenDatesRequest
	26, // 46: driver_history.DriverHistoryService.GetTotalCommandFeesByDay:input_type -> driver_history.GetTotalCommandFeesByDayRequest
	29, // 47: driver_history.DriverHistoryService.TrackJoinZone:input_type -> driver_history.TrackJoinZoneRequest
	30, // 48: driver_history.DriverHistoryService.TrackLeaveZone:input_type -> driver_history.TrackLeaveZoneRequest
	31, // 49: driver_history.DriverHistoryService.TrackAcceptCommand:input_type -> driver_history.TrackAcceptCommandRequest
	32, // 50: driver_history.DriverHistoryService.TrackShareCommand:input_type -> driver_history.TrackShareCommandRequest
	33, // 51: driver_history.DriverHistoryService.TrackDeliverCommand:input_type -> driver_history.TrackDeliverCommandRequest
	2,  // 52: driver_history.DriverHistoryService.CreateDriverHistory:output_type -> driver_history.DriverHistoryResponse
	2,  // 53: driver_history.DriverHistoryService.GetDriverHistoryByID:output_type -> driver_history.DriverHistoryResponse
	3,  // 54: driver_history.DriverHistoryService.ReadAllDriverHistories:output_type -> driver_history.DriverHistoryListResponse
	2,  // 55: driver_history.DriverHistoryService.UpdateDriverHistory:output_type -> driver_history.DriverHistoryResponse
	35, // 56: driver_history.DriverHistoryService.DeleteDriverHistory:output_type -> google.protobuf.Empty
	3,  // 57: driver_history.DriverHistoryService.GetDriverHistoriesByDriverID:output_type -> driver_history.DriverHistoryListResponse
	3,  // 58: driver_history.DriverHistoryService.GetDriverHistoriesByAction:output_type -> driver_history.DriverHistoryListResponse
	3,  // 59: driver_history.DriverHistoryService.GetDriverHistoriesByDriverIDAndAction:output_type -> driver_history.DriverHistoryListResponse
	3,  // 60: driver_history.DriverHistoryService.GetDriverHistoriesByDriverIDBetweenDates:output_type -> driver_history.DriverHistoryListResponse
	3,  // 61: driver_history.DriverHistoryService.GetDriverHistoriesByActionBetweenDates:output_type -> driver_history.DriverHistoryListResponse
	17, // 62: driver_history.DriverHistoryService.CountAcceptedCommandsByDay:output_type -> driver_history.CommandCountByDayListResponse
	17, // 63: driver_history.DriverHistoryService.CountAcceptedCommandsByDayForAllDrivers:output_type -> driver_history.CommandCountByDayListResponse
	20, // 64: driver_history.DriverHistoryService.CountActionsByDriver:output_type -> driver_history.ActionCountListResponse
	24, // 65: driver_history.DriverHistoryService.GetWorkedHoursByDay:output_type -> driver_history.WorkedHoursResponse
	25, // 66: driver_history.DriverHistoryService.GetWorkedHoursBetweenDates:output_type -> driver_history.WorkedHoursListResponse
	28, // 67: driver_history.DriverHistoryService.GetTotalCommandFeesByDay:output_type -> driver_history.FeeByDayListResponse
	2,  // 68: driver_history.DriverHistoryService.TrackJoinZone:output_type -> driver_history.DriverHistoryResponse
	2,  // 69: driver_history.DriverHistoryService.TrackLeaveZone:output_type -> driver_history.DriverHistoryResponse
	2,  // 70: driver_history.DriverHistoryService.TrackAcceptCommand:output_type -> driver_history.DriverHistoryResponse
	2,  // 71: driver_history.DriverHistoryService.TrackShareCommand:output_type -> driver_history.DriverHistoryResponse
	2,  // 72: driver_history.DriverHistoryService.TrackDeliverCommand:output_type -> driver_history.DriverHistoryResponse
	52, // [52:73] is the sub-list for method output_type
	31, // [31:52] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_driver_history_proto_init() }
func file_driver_history_proto_init() {
	if File_driver_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_history_proto_rawDesc), len(file_driver_history_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_history_proto_goTypes,
		DependencyIndexes: file_driver_history_proto_depIdxs,
		EnumInfos:         file_driver_history_proto_enumTypes,
		MessageInfos:      file_driver_history_proto_msgTypes,
	}.Build()
	File_driver_history_proto = out.File
	file_driver_history_proto_goTypes = nil
	file_driver_history_proto_depIdxs = nil
}
