// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: driver.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverStatus int32

const (
	DriverStatus_DRIVER_STATUS_UNSPECIFIED DriverStatus = 0
	DriverStatus_OFFLINE                   DriverStatus = 1
	DriverStatus_ONLINE                    DriverStatus = 2
	DriverStatus_BUSY                      DriverStatus = 3
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "DRIVER_STATUS_UNSPECIFIED",
		1: "OFFLINE",
		2: "ONLINE",
		3: "BUSY",
	}
	DriverStatus_value = map[string]int32{
		"DRIVER_STATUS_UNSPECIFIED": 0,
		"OFFLINE":                   1,
		"ONLINE":                    2,
		"BUSY":                      3,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_driver_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_driver_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

type PickupType int32

const (
	PickupType_PICKUP_TYPE_UNSPECIFIED PickupType = 0
	PickupType_PICKUP                  PickupType = 1
	PickupType_INTERCHANGE             PickupType = 2
)

// Enum value maps for PickupType.
var (
	PickupType_name = map[int32]string{
		0: "PICKUP_TYPE_UNSPECIFIED",
		1: "PICKUP",
		2: "INTERCHANGE",
	}
	PickupType_value = map[string]int32{
		"PICKUP_TYPE_UNSPECIFIED": 0,
		"PICKUP":                  1,
		"INTERCHANGE":             2,
	}
)

func (x PickupType) Enum() *PickupType {
	p := new(PickupType)
	*p = x
	return p
}

func (x PickupType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PickupType) Descriptor() protoreflect.EnumDescriptor {
	return file_driver_proto_enumTypes[1].Descriptor()
}

func (PickupType) Type() protoreflect.EnumType {
	return &file_driver_proto_enumTypes[1]
}

func (x PickupType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PickupType.Descriptor instead.
func (PickupType) EnumDescriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{1}
}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DriverStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=cat.DriverStatus" json:"status,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	ZoneId        string                 `protobuf:"bytes,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Zone          *Zone                  `protobuf:"bytes,9,opt,name=zone,proto3" json:"zone,omitempty"`
	Commands      []*Command             `protobuf:"bytes,10,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_DRIVER_STATUS_UNSPECIFIED
}

func (x *Driver) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Driver) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Driver) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Driver) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Driver) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Driver) GetZone() *Zone {
	if x != nil {
		return x.Zone
	}
	return nil
}

func (x *Driver) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type LeaveZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveZoneRequest) Reset() {
	*x = LeaveZoneRequest{}
	mi := &file_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveZoneRequest) ProtoMessage() {}

func (x *LeaveZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveZoneRequest.ProtoReflect.Descriptor instead.
func (*LeaveZoneRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{1}
}

type JoinZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Lat           float32                `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinZoneRequest) Reset() {
	*x = JoinZoneRequest{}
	mi := &file_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinZoneRequest) ProtoMessage() {}

func (x *JoinZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinZoneRequest.ProtoReflect.Descriptor instead.
func (*JoinZoneRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{2}
}

func (x *JoinZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *JoinZoneRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *JoinZoneRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type JoinZoneRespone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          *Zone                  `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinZoneRespone) Reset() {
	*x = JoinZoneRespone{}
	mi := &file_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinZoneRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinZoneRespone) ProtoMessage() {}

func (x *JoinZoneRespone) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinZoneRespone.ProtoReflect.Descriptor instead.
func (*JoinZoneRespone) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{3}
}

func (x *JoinZoneRespone) GetZone() *Zone {
	if x != nil {
		return x.Zone
	}
	return nil
}

type LeaveZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveZoneResponse) Reset() {
	*x = LeaveZoneResponse{}
	mi := &file_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveZoneResponse) ProtoMessage() {}

func (x *LeaveZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveZoneResponse.ProtoReflect.Descriptor instead.
func (*LeaveZoneResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveZoneResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatusResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type AcceptCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCommandRequest) Reset() {
	*x = AcceptCommandRequest{}
	mi := &file_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCommandRequest) ProtoMessage() {}

func (x *AcceptCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCommandRequest.ProtoReflect.Descriptor instead.
func (*AcceptCommandRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type RouteWaypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	SnapDistance  float64                `protobuf:"fixed64,4,opt,name=snap_distance,json=snapDistance,proto3" json:"snap_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteWaypoint) Reset() {
	*x = RouteWaypoint{}
	mi := &file_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteWaypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteWaypoint) ProtoMessage() {}

func (x *RouteWaypoint) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteWaypoint.ProtoReflect.Descriptor instead.
func (*RouteWaypoint) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{8}
}

func (x *RouteWaypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteWaypoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RouteWaypoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RouteWaypoint) GetSnapDistance() float64 {
	if x != nil {
		return x.SnapDistance
	}
	return 0
}

type Step struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Geometry         string                 `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Distance         float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration         float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Ref              string                 `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
	Mode             string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	ManeuverType     string                 `protobuf:"bytes,7,opt,name=maneuver_type,json=maneuverType,proto3" json:"maneuver_type,omitempty"`
	ManeuverModifier string                 `protobuf:"bytes,8,opt,name=maneuver_modifier,json=maneuverModifier,proto3" json:"maneuver_modifier,omitempty"`
	Instruction      string                 `protobuf:"bytes,9,opt,name=instruction,proto3" json:"instruction,omitempty"`
	ManeuverLat      float64                `protobuf:"fixed64,10,opt,name=maneuver_lat,json=maneuverLat,proto3" json:"maneuver_lat,omitempty"`
	ManeuverLon      float64                `protobuf:"fixed64,11,opt,name=maneuver_lon,json=maneuverLon,proto3" json:"maneuver_lon,omitempty"`
	BearingBefore    int32                  `protobuf:"varint,12,opt,name=bearing_before,json=bearingBefore,proto3" json:"bearing_before,omitempty"`
	BearingAfter     int32                  `protobuf:"varint,13,opt,name=bearing_after,json=bearingAfter,proto3" json:"bearing_after,omitempty"`
	Exit             int32                  `protobuf:"varint,14,opt,name=exit,proto3" json:"exit,omitempty"`
	DrivingSide      string                 `protobuf:"bytes,15,opt,name=driving_side,json=drivingSide,proto3" json:"driving_side,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{9}
}

func (x *Step) GetGeometry() string {
	if x != nil {
		return x.Geometry
	}
	return ""
}

func (x *Step) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Step) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Step) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Step) GetManeuverType() string {
	if x != nil {
		return x.ManeuverType
	}
	return ""
}

func (x *Step) GetManeuverModifier() string {
	if x != nil {
		return x.ManeuverModifier
	}
	return ""
}

func (x *Step) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Step) GetManeuverLat() float64 {
	if x != nil {
		return x.ManeuverLat
	}
	return 0
}

func (x *Step) GetManeuverLon() float64 {
	if x != nil {
		return x.ManeuverLon
	}
	return 0
}

func (x *Step) GetBearingBefore() int32 {
	if x != nil {
		return x.BearingBefore
	}
	return 0
}

func (x *Step) GetBearingAfter() int32 {
	if x != nil {
		return x.BearingAfter
	}
	return 0
}

func (x *Step) GetExit() int32 {
	if x != nil {
		return x.Exit
	}
	return 0
}

func (x *Step) GetDrivingSide() string {
	if x != nil {
		return x.DrivingSide
	}
	return ""
}

type Leg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Steps         []*Step                `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leg) Reset() {
	*x = Leg{}
	mi := &file_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{10}
}

func (x *Leg) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Leg) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Leg) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Leg) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type FindPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPathRequest) Reset() {
	*x = FindPathRequest{}
	mi := &file_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPathRequest) ProtoMessage() {}

func (x *FindPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPathRequest.ProtoReflect.Descriptor instead.
func (*FindPathRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{11}
}

func (x *FindPathRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FindPathRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Path struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Geometry        string                 `protobuf:"bytes,2,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Distance        float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration        float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`
	DurationTypical float64                `protobuf:"fixed64,5,opt,name=duration_typical,json=durationTypical,proto3" json:"duration_typical,omitempty"`
	MinLat          float64                `protobuf:"fixed64,6,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon          float64                `protobuf:"fixed64,7,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat          float64                `protobuf:"fixed64,8,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon          float64                `protobuf:"fixed64,9,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	Waypoints       []*RouteWaypoint       `protobuf:"bytes,10,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	Legs            []*Leg                 `protobuf:"bytes,11,rep,name=legs,proto3" json:"legs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{12}
}

func (x *Path) GetGeometry() string {
	if x != nil {
		return x.Geometry
	}
	return ""
}

func (x *Path) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Path) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Path) GetDurationTypical() float64 {
	if x != nil {
		return x.DurationTypical
	}
	return 0
}

func (x *Path) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *Path) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *Path) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *Path) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *Path) GetWaypoints() []*RouteWaypoint {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *Path) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

type FindPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	Path          *Path                  `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPathResponse) Reset() {
	*x = FindPathResponse{}
	mi := &file_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPathResponse) ProtoMessage() {}

func (x *FindPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPathResponse.ProtoReflect.Descriptor instead.
func (*FindPathResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{13}
}

func (x *FindPathResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *FindPathResponse) GetPath() *Path {
	if x != nil {
		return x.Path
	}
	return nil
}

type PickupCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          PickupType             `protobuf:"varint,2,opt,name=type,proto3,enum=cat.PickupType" json:"type,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupCommandRequest) Reset() {
	*x = PickupCommandRequest{}
	mi := &file_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupCommandRequest) ProtoMessage() {}

func (x *PickupCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupCommandRequest.ProtoReflect.Descriptor instead.
func (*PickupCommandRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{14}
}

func (x *PickupCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PickupCommandRequest) GetType() PickupType {
	if x != nil {
		return x.Type
	}
	return PickupType_PICKUP_TYPE_UNSPECIFIED
}

func (x *PickupCommandRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PickupCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupCommandResponse) Reset() {
	*x = PickupCommandResponse{}
	mi := &file_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupCommandResponse) ProtoMessage() {}

func (x *PickupCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupCommandResponse.ProtoReflect.Descriptor instead.
func (*PickupCommandResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{15}
}

func (x *PickupCommandResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type DeliverCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverCommandRequest) Reset() {
	*x = DeliverCommandRequest{}
	mi := &file_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverCommandRequest) ProtoMessage() {}

func (x *DeliverCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverCommandRequest.ProtoReflect.Descriptor instead.
func (*DeliverCommandRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{16}
}

func (x *DeliverCommandRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeliverCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type DeliverCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverCommandResponse) Reset() {
	*x = DeliverCommandResponse{}
	mi := &file_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverCommandResponse) ProtoMessage() {}

func (x *DeliverCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverCommandResponse.ProtoReflect.Descriptor instead.
func (*DeliverCommandResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{17}
}

func (x *DeliverCommandResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type ChangeSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSlotRequest) Reset() {
	*x = ChangeSlotRequest{}
	mi := &file_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSlotRequest) ProtoMessage() {}

func (x *ChangeSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSlotRequest.ProtoReflect.Descriptor instead.
func (*ChangeSlotRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{18}
}

func (x *ChangeSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

type ChangeSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSlotResponse) Reset() {
	*x = ChangeSlotResponse{}
	mi := &file_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSlotResponse) ProtoMessage() {}

func (x *ChangeSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSlotResponse.ProtoReflect.Descriptor instead.
func (*ChangeSlotResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{19}
}

func (x *ChangeSlotResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type AcceptCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCommandResponse) Reset() {
	*x = AcceptCommandResponse{}
	mi := &file_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCommandResponse) ProtoMessage() {}

func (x *AcceptCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCommandResponse.ProtoReflect.Descriptor instead.
func (*AcceptCommandResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{20}
}

func (x *AcceptCommandResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type AcceptSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptSlotRequest) Reset() {
	*x = AcceptSlotRequest{}
	mi := &file_driver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptSlotRequest) ProtoMessage() {}

func (x *AcceptSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptSlotRequest.ProtoReflect.Descriptor instead.
func (*AcceptSlotRequest) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{21}
}

func (x *AcceptSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

type AcceptSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptSlotResponse) Reset() {
	*x = AcceptSlotResponse{}
	mi := &file_driver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptSlotResponse) ProtoMessage() {}

func (x *AcceptSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptSlotResponse.ProtoReflect.Descriptor instead.
func (*AcceptSlotResponse) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{22}
}

func (x *AcceptSlotResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

var File_driver_proto protoreflect.FileDescriptor

const file_driver_proto_rawDesc = "" +
	"\n" +
	"\fdriver.proto\x12\x03cat\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\x1a\n" +
	"zone.proto\x1a\rcommand.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.cat.DriverStatusR\x06status\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\tR\x06zoneId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\x04zone\x18\t \x01(\v2\t.cat.ZoneR\x04zone\x12(\n" +
	"\bcommands\x18\n" +
	" \x03(\v2\f.cat.CommandR\bcommands\"\x12\n" +
	"\x10LeaveZoneRequest\"z\n" +
	"\x0fJoinZoneRequest\x12!\n" +
	"\azone_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06zoneId\x12!\n" +
	"\x03lat\x18\x02 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\xb4B-\x00\x00\xb4\xc2R\x03lat\x12!\n" +
	"\x03lon\x18\x03 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x004C-\x00\x004\xc3R\x03lon\"0\n" +
	"\x0fJoinZoneRespone\x12\x1d\n" +
	"\x04zone\x18\x01 \x01(\v2\t.cat.ZoneR\x04zone\"/\n" +
	"\x11LeaveZoneResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"N\n" +
	"\x13UpdateStatusRequest\x127\n" +
	"\x06status\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1aR\tAVAILABLER\x04BUSYR\aOFFLINER\x06status\"2\n" +
	"\x14UpdateStatusResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"?\n" +
	"\x14AcceptCommandRequest\x12'\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tcommandId\"l\n" +
	"\rRouteWaypoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12#\n" +
	"\rsnap_distance\x18\x04 \x01(\x01R\fsnapDistance\"\xd1\x03\n" +
	"\x04Step\x12\x1a\n" +
	"\bgeometry\x18\x01 \x01(\tR\bgeometry\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\tR\x03ref\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12#\n" +
	"\rmaneuver_type\x18\a \x01(\tR\fmaneuverType\x12+\n" +
	"\x11maneuver_modifier\x18\b \x01(\tR\x10maneuverModifier\x12 \n" +
	"\vinstruction\x18\t \x01(\tR\vinstruction\x12!\n" +
	"\fmaneuver_lat\x18\n" +
	" \x01(\x01R\vmaneuverLat\x12!\n" +
	"\fmaneuver_lon\x18\v \x01(\x01R\vmaneuverLon\x12%\n" +
	"\x0ebearing_before\x18\f \x01(\x05R\rbearingBefore\x12#\n" +
	"\rbearing_after\x18\r \x01(\x05R\fbearingAfter\x12\x12\n" +
	"\x04exit\x18\x0e \x01(\x05R\x04exit\x12!\n" +
	"\fdriving_side\x18\x0f \x01(\tR\vdrivingSide\"x\n" +
	"\x03Leg\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1f\n" +
	"\x05steps\x18\x04 \x03(\v2\t.cat.StepR\x05steps\"g\n" +
	"\x0fFindPathRequest\x12)\n" +
	"\x03lat\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80V@!\x00\x00\x00\x00\x00\x80V\xc0R\x03lat\x12)\n" +
	"\x03lon\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80f@!\x00\x00\x00\x00\x00\x80f\xc0R\x03lon\"\xb9\x02\n" +
	"\x04Path\x12\x1a\n" +
	"\bgeometry\x18\x02 \x01(\tR\bgeometry\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\x12)\n" +
	"\x10duration_typical\x18\x05 \x01(\x01R\x0fdurationTypical\x12\x17\n" +
	"\amin_lat\x18\x06 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\a \x01(\x01R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\b \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\t \x01(\x01R\x06maxLon\x120\n" +
	"\twaypoints\x18\n" +
	" \x03(\v2\x12.cat.RouteWaypointR\twaypoints\x12\x1c\n" +
	"\x04legs\x18\v \x03(\v2\b.cat.LegR\x04legs\"M\n" +
	"\x10FindPathResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\x12\x1d\n" +
	"\x04path\x18\x02 \x01(\v2\t.cat.PathR\x04path\"\x82\x01\n" +
	"\x14PickupCommandRequest\x12'\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tcommandId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.cat.PickupTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"3\n" +
	"\x15PickupCommandResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"_\n" +
	"\x15DeliverCommandRequest\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x06\x18\x06R\x04code\x12'\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tcommandId\"4\n" +
	"\x16DeliverCommandResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"6\n" +
	"\x11ChangeSlotRequest\x12!\n" +
	"\aslot_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06slotId\"0\n" +
	"\x12ChangeSlotResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"3\n" +
	"\x15AcceptCommandResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"6\n" +
	"\x11AcceptSlotRequest\x12!\n" +
	"\aslot_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06slotId\"0\n" +
	"\x12AcceptSlotResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse*P\n" +
	"\fDriverStatus\x12\x1d\n" +
	"\x19DRIVER_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x02\x12\b\n" +
	"\x04BUSY\x10\x03*F\n" +
	"\n" +
	"PickupType\x12\x1b\n" +
	"\x17PICKUP_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PICKUP\x10\x01\x12\x0f\n" +
	"\vINTERCHANGE\x10\x022\xe2\a\n" +
	"\rDriverService\x12N\n" +
	"\tGetDrvier\x12\x15.cat.LeaveZoneRequest\x1a\v.cat.Driver\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/abyssin/driver/me\x12U\n" +
	"\tLeaveZone\x12\x15.cat.LeaveZoneRequest\x1a\x16.cat.LeaveZoneResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/abyssin/leave\x12Z\n" +
	"\bJoinZone\x12\x14.cat.JoinZoneRequest\x1a\x14.cat.JoinZoneRespone\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/abyssin/join/{zone_id}\x12b\n" +
	"\fUpdateStatus\x12\x18.cat.UpdateStatusRequest\x1a\x19.cat.UpdateStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/abyssin/status\x12l\n" +
	"\rAcceptCommand\x12\x19.cat.AcceptCommandRequest\x1a\x1a.cat.AcceptCommandResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/abyssin/acceptCommand\x12l\n" +
	"\rPickupCommand\x12\x19.cat.PickupCommandRequest\x1a\x1a.cat.PickupCommandResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/abyssin/pickupCommand\x12`\n" +
	"\n" +
	"AcceptSlot\x12\x16.cat.AcceptSlotRequest\x1a\x17.cat.AcceptSlotResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/abyssin/acceptSlot\x12X\n" +
	"\bFindPath\x12\x14.cat.FindPathRequest\x1a\x15.cat.FindPathResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/abyssin/findPath\x12`\n" +
	"\n" +
	"ChangeSlot\x12\x16.cat.ChangeSlotRequest\x1a\x17.cat.ChangeSlotResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/abyssin/changeSlot\x12p\n" +
	"\x0eDeliverCommand\x12\x1a.cat.DeliverCommandRequest\x1a\x1b.cat.DeliverCommandResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/abyssin/deliverCommandBQ\n" +
	"\acom.catB\vDriverProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03CXX\xaa\x02\x03Cat\xca\x02\x03Cat\xe2\x02\x0fCat\\GPBMetadata\xea\x02\x03Catb\x06proto3"

var (
	file_driver_proto_rawDescOnce sync.Once
	file_driver_proto_rawDescData []byte
)

func file_driver_proto_rawDescGZIP() []byte {
	file_driver_proto_rawDescOnce.Do(func() {
		file_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)))
	})
	return file_driver_proto_rawDescData
}

var file_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_driver_proto_goTypes = []any{
	(DriverStatus)(0),              // 0: cat.DriverStatus
	(PickupType)(0),                // 1: cat.PickupType
	(*Driver)(nil),                 // 2: cat.Driver
	(*LeaveZoneRequest)(nil),       // 3: cat.LeaveZoneRequest
	(*JoinZoneRequest)(nil),        // 4: cat.JoinZoneRequest
	(*JoinZoneRespone)(nil),        // 5: cat.JoinZoneRespone
	(*LeaveZoneResponse)(nil),      // 6: cat.LeaveZoneResponse
	(*UpdateStatusRequest)(nil),    // 7: cat.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),   // 8: cat.UpdateStatusResponse
	(*AcceptCommandRequest)(nil),   // 9: cat.AcceptCommandRequest
	(*RouteWaypoint)(nil),          // 10: cat.RouteWaypoint
	(*Step)(nil),                   // 11: cat.Step
	(*Leg)(nil),                    // 12: cat.Leg
	(*FindPathRequest)(nil),        // 13: cat.FindPathRequest
	(*Path)(nil),                   // 14: cat.Path
	(*FindPathResponse)(nil),       // 15: cat.FindPathResponse
	(*PickupCommandRequest)(nil),   // 16: cat.PickupCommandRequest
	(*PickupCommandResponse)(nil),  // 17: cat.PickupCommandResponse
	(*DeliverCommandRequest)(nil),  // 18: cat.DeliverCommandRequest
	(*DeliverCommandResponse)(nil), // 19: cat.DeliverCommandResponse
	(*ChangeSlotRequest)(nil),      // 20: cat.ChangeSlotRequest
	(*ChangeSlotResponse)(nil),     // 21: cat.ChangeSlotResponse
	(*AcceptCommandResponse)(nil),  // 22: cat.AcceptCommandResponse
	(*AcceptSlotRequest)(nil),      // 23: cat.AcceptSlotRequest
	(*AcceptSlotResponse)(nil),     // 24: cat.AcceptSlotResponse
	(*timestamppb.Timestamp)(nil),  // 25: google.protobuf.Timestamp
	(*Zone)(nil),                   // 26: cat.Zone
	(*Command)(nil),                // 27: cat.Command
}
var file_driver_proto_depIdxs = []int32{
	0,  // 0: cat.Driver.status:type_name -> cat.DriverStatus
	25, // 1: cat.Driver.created_at:type_name -> google.protobuf.Timestamp
	25, // 2: cat.Driver.updated_at:type_name -> google.protobuf.Timestamp
	26, // 3: cat.Driver.zone:type_name -> cat.Zone
	27, // 4: cat.Driver.commands:type_name -> cat.Command
	26, // 5: cat.JoinZoneRespone.zone:type_name -> cat.Zone
	11, // 6: cat.Leg.steps:type_name -> cat.Step
	10, // 7: cat.Path.waypoints:type_name -> cat.RouteWaypoint
	12, // 8: cat.Path.legs:type_name -> cat.Leg
	14, // 9: cat.FindPathResponse.path:type_name -> cat.Path
	1,  // 10: cat.PickupCommandRequest.type:type_name -> cat.PickupType
	3,  // 11: cat.DriverService.GetDrvier:input_type -> cat.LeaveZoneRequest
	3,  // 12: cat.DriverService.LeaveZone:input_type -> cat.LeaveZoneRequest
	4,  // 13: cat.DriverService.JoinZone:input_type -> cat.JoinZoneRequest
	7,  // 14: cat.DriverService.UpdateStatus:input_type -> cat.UpdateStatusRequest
	9,  // 15: cat.DriverService.AcceptCommand:input_type -> cat.AcceptCommandRequest
	16, // 16: cat.DriverService.PickupCommand:input_type -> cat.PickupCommandRequest
	23, // 17: cat.DriverService.AcceptSlot:input_type -> cat.AcceptSlotRequest
	13, // 18: cat.DriverService.FindPath:input_type -> cat.FindPathRequest
	20, // 19: cat.DriverService.ChangeSlot:input_type -> cat.ChangeSlotRequest
	18, // 20: cat.DriverService.DeliverCommand:input_type -> cat.DeliverCommandRequest
	2,  // 21: cat.DriverService.GetDrvier:output_type -> cat.Driver
	6,  // 22: cat.DriverService.LeaveZone:output_type -> cat.LeaveZoneResponse
	5,  // 23: cat.DriverService.JoinZone:output_type -> cat.JoinZoneRespone
	8,  // 24: cat.DriverService.UpdateStatus:output_type -> cat.UpdateStatusResponse
	22, // 25: cat.DriverService.AcceptCommand:output_type -> cat.AcceptCommandResponse
	17, // 26: cat.DriverService.PickupCommand:output_type -> cat.PickupCommandResponse
	24, // 27: cat.DriverService.AcceptSlot:output_type -> cat.AcceptSlotResponse
	15, // 28: cat.DriverService.FindPath:output_type -> cat.FindPathResponse
	21, // 29: cat.DriverService.ChangeSlot:output_type -> cat.ChangeSlotResponse
	19, // 30: cat.DriverService.DeliverCommand:output_type -> cat.DeliverCommandResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_driver_proto_init() }
func file_driver_proto_init() {
	if File_driver_proto != nil {
		return
	}
	file_zone_proto_init()
	file_command_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_proto_goTypes,
		DependencyIndexes: file_driver_proto_depIdxs,
		EnumInfos:         file_driver_proto_enumTypes,
		MessageInfos:      file_driver_proto_msgTypes,
	}.Build()
	File_driver_proto = out.File
	file_driver_proto_goTypes = nil
	file_driver_proto_depIdxs = nil
}
