// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_SearchProductByName_FullMethodName     = "/cat.ProductService/SearchProductByName"
	ProductService_GetProductsByStoreID_FullMethodName    = "/cat.ProductService/GetProductsByStoreID"
	ProductService_SearchProductsByStoreID_FullMethodName = "/cat.ProductService/SearchProductsByStoreID"
	ProductService_GetProductByID_FullMethodName          = "/cat.ProductService/GetProductByID"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	SearchProductByName(ctx context.Context, in *SearchProductByNameRequest, opts ...grpc.CallOption) (*SearchProductByNameResponse, error)
	GetProductsByStoreID(ctx context.Context, in *GetProductsByStoreIDRequest, opts ...grpc.CallOption) (*GetProductsByStoreIDResponse, error)
	SearchProductsByStoreID(ctx context.Context, in *SearchProductsByStoreIDRequest, opts ...grpc.CallOption) (*SearchProductsByStoreIDResponse, error)
	GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) SearchProductByName(ctx context.Context, in *SearchProductByNameRequest, opts ...grpc.CallOption) (*SearchProductByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductByNameResponse)
	err := c.cc.Invoke(ctx, ProductService_SearchProductByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductsByStoreID(ctx context.Context, in *GetProductsByStoreIDRequest, opts ...grpc.CallOption) (*GetProductsByStoreIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsByStoreIDResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductsByStoreID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SearchProductsByStoreID(ctx context.Context, in *SearchProductsByStoreIDRequest, opts ...grpc.CallOption) (*SearchProductsByStoreIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsByStoreIDResponse)
	err := c.cc.Invoke(ctx, ProductService_SearchProductsByStoreID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductByIDResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	SearchProductByName(context.Context, *SearchProductByNameRequest) (*SearchProductByNameResponse, error)
	GetProductsByStoreID(context.Context, *GetProductsByStoreIDRequest) (*GetProductsByStoreIDResponse, error)
	SearchProductsByStoreID(context.Context, *SearchProductsByStoreIDRequest) (*SearchProductsByStoreIDResponse, error)
	GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) SearchProductByName(context.Context, *SearchProductByNameRequest) (*SearchProductByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProductByName not implemented")
}
func (UnimplementedProductServiceServer) GetProductsByStoreID(context.Context, *GetProductsByStoreIDRequest) (*GetProductsByStoreIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsByStoreID not implemented")
}
func (UnimplementedProductServiceServer) SearchProductsByStoreID(context.Context, *SearchProductsByStoreIDRequest) (*SearchProductsByStoreIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProductsByStoreID not implemented")
}
func (UnimplementedProductServiceServer) GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_SearchProductByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SearchProductByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_SearchProductByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SearchProductByName(ctx, req.(*SearchProductByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductsByStoreID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsByStoreIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductsByStoreID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductsByStoreID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductsByStoreID(ctx, req.(*GetProductsByStoreIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SearchProductsByStoreID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsByStoreIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SearchProductsByStoreID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_SearchProductsByStoreID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SearchProductsByStoreID(ctx, req.(*SearchProductsByStoreIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductByID(ctx, req.(*GetProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cat.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchProductByName",
			Handler:    _ProductService_SearchProductByName_Handler,
		},
		{
			MethodName: "GetProductsByStoreID",
			Handler:    _ProductService_GetProductsByStoreID_Handler,
		},
		{
			MethodName: "SearchProductsByStoreID",
			Handler:    _ProductService_SearchProductsByStoreID_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _ProductService_GetProductByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
