// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: store.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Supplierid    string                 `protobuf:"bytes,3,opt,name=supplierid,proto3" json:"supplierid,omitempty"`
	Supplier      *Supplier              `protobuf:"bytes,4,opt,name=supplier,proto3" json:"supplier,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Products      []*Product             `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	Categories    []*Storecategory       `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Galeries      []*Storegalery         `protobuf:"bytes,8,rep,name=galeries,proto3" json:"galeries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Store) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Store) GetSupplierid() string {
	if x != nil {
		return x.Supplierid
	}
	return ""
}

func (x *Store) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

func (x *Store) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Store) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Store) GetCategories() []*Storecategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Store) GetGaleries() []*Storegalery {
	if x != nil {
		return x.Galeries
	}
	return nil
}

type SearchStoreByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStoreByNameRequest) Reset() {
	*x = SearchStoreByNameRequest{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStoreByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStoreByNameRequest) ProtoMessage() {}

func (x *SearchStoreByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStoreByNameRequest.ProtoReflect.Descriptor instead.
func (*SearchStoreByNameRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *SearchStoreByNameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchStoreByNameRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchStoreByNameRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchStoreByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStoreByNameResponse) Reset() {
	*x = SearchStoreByNameResponse{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStoreByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStoreByNameResponse) ProtoMessage() {}

func (x *SearchStoreByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStoreByNameResponse.ProtoReflect.Descriptor instead.
func (*SearchStoreByNameResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{2}
}

func (x *SearchStoreByNameResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *SearchStoreByNameResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\x03cat\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\x1a\raddress.proto\x1a\x0esupplier.proto\x1a\x13storecategory.proto\x1a\rproduct.proto\x1a\x11storegalery.proto\"\xcf\x02\n" +
	"\x05Store\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1f\n" +
	"\x05title\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x05title\x12(\n" +
	"\n" +
	"supplierid\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"supplierid\x12)\n" +
	"\bsupplier\x18\x04 \x01(\v2\r.cat.SupplierR\bsupplier\x12*\n" +
	"\taddresses\x18\x05 \x03(\v2\f.cat.AddressR\taddresses\x12(\n" +
	"\bproducts\x18\x06 \x03(\v2\f.cat.ProductR\bproducts\x122\n" +
	"\n" +
	"categories\x18\a \x03(\v2\x12.cat.StorecategoryR\n" +
	"categories\x12,\n" +
	"\bgaleries\x18\b \x03(\v2\x10.cat.StoregaleryR\bgaleries\"}\n" +
	"\x18SearchStoreByNameRequest\x12\x1f\n" +
	"\x05query\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x05query\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x06offset\x12\x1f\n" +
	"\x05limit\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\x05limit\"U\n" +
	"\x19SearchStoreByNameResponse\x12\"\n" +
	"\x06stores\x18\x01 \x03(\v2\n" +
	".cat.StoreR\x06stores\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\x84\x01\n" +
	"\fStoreService\x12t\n" +
	"\x11SearchStoreByName\x12\x1d.cat.SearchStoreByNameRequest\x1a\x1e.cat.SearchStoreByNameResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/ragdoll/store/searchBP\n" +
	"\acom.catB\n" +
	"StoreProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03CXX\xaa\x02\x03Cat\xca\x02\x03Cat\xe2\x02\x0fCat\\GPBMetadata\xea\x02\x03Catb\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_store_proto_goTypes = []any{
	(*Store)(nil),                     // 0: cat.Store
	(*SearchStoreByNameRequest)(nil),  // 1: cat.SearchStoreByNameRequest
	(*SearchStoreByNameResponse)(nil), // 2: cat.SearchStoreByNameResponse
	(*Supplier)(nil),                  // 3: cat.Supplier
	(*Address)(nil),                   // 4: cat.Address
	(*Product)(nil),                   // 5: cat.Product
	(*Storecategory)(nil),             // 6: cat.Storecategory
	(*Storegalery)(nil),               // 7: cat.Storegalery
}
var file_store_proto_depIdxs = []int32{
	3, // 0: cat.Store.supplier:type_name -> cat.Supplier
	4, // 1: cat.Store.addresses:type_name -> cat.Address
	5, // 2: cat.Store.products:type_name -> cat.Product
	6, // 3: cat.Store.categories:type_name -> cat.Storecategory
	7, // 4: cat.Store.galeries:type_name -> cat.Storegalery
	0, // 5: cat.SearchStoreByNameResponse.stores:type_name -> cat.Store
	1, // 6: cat.StoreService.SearchStoreByName:input_type -> cat.SearchStoreByNameRequest
	2, // 7: cat.StoreService.SearchStoreByName:output_type -> cat.SearchStoreByNameResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	file_address_proto_init()
	file_supplier_proto_init()
	file_storecategory_proto_init()
	file_product_proto_init()
	file_storegalery_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
