// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: command.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Position) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Command struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status              int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ValidationCode      string                 `protobuf:"bytes,3,opt,name=validation_code,json=validationCode,proto3" json:"validation_code,omitempty"`
	Path                string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Size                string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	OriginPosition      *Position              `protobuf:"bytes,6,opt,name=origin_position,json=originPosition,proto3" json:"origin_position,omitempty"`
	DestinationPosition *Position              `protobuf:"bytes,7,opt,name=destination_position,json=destinationPosition,proto3" json:"destination_position,omitempty"`
	ZoneId              string                 `protobuf:"bytes,8,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	DriverId            *string                `protobuf:"bytes,9,opt,name=driver_id,json=driverId,proto3,oneof" json:"driver_id,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Command) GetValidationCode() string {
	if x != nil {
		return x.ValidationCode
	}
	return ""
}

func (x *Command) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Command) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Command) GetOriginPosition() *Position {
	if x != nil {
		return x.OriginPosition
	}
	return nil
}

func (x *Command) GetDestinationPosition() *Position {
	if x != nil {
		return x.DestinationPosition
	}
	return nil
}

func (x *Command) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Command) GetDriverId() string {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return ""
}

func (x *Command) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Command) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateCommandRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	OriginPosition      *Position              `protobuf:"bytes,3,opt,name=origin_position,json=originPosition,proto3" json:"origin_position,omitempty"`
	DestinationPosition *Position              `protobuf:"bytes,4,opt,name=destination_position,json=destinationPosition,proto3" json:"destination_position,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateCommandRequest) Reset() {
	*x = CreateCommandRequest{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandRequest) ProtoMessage() {}

func (x *CreateCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCommandRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CreateCommandRequest) GetOriginPosition() *Position {
	if x != nil {
		return x.OriginPosition
	}
	return nil
}

func (x *CreateCommandRequest) GetDestinationPosition() *Position {
	if x != nil {
		return x.DestinationPosition
	}
	return nil
}

type CreateCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      int32                  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandResponse) Reset() {
	*x = CreateCommandResponse{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandResponse) ProtoMessage() {}

func (x *CreateCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandResponse.ProtoReflect.Descriptor instead.
func (*CreateCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommandResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type ReadAllCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCommandsRequest) Reset() {
	*x = ReadAllCommandsRequest{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCommandsRequest) ProtoMessage() {}

func (x *ReadAllCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCommandsRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCommandsRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAllCommandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadAllCommandsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadAllCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCommandsResponse) Reset() {
	*x = ReadAllCommandsResponse{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCommandsResponse) ProtoMessage() {}

func (x *ReadAllCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCommandsResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCommandsResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllCommandsResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ReadCommandsByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommandsByStatusRequest) Reset() {
	*x = ReadCommandsByStatusRequest{}
	mi := &file_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommandsByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommandsByStatusRequest) ProtoMessage() {}

func (x *ReadCommandsByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommandsByStatusRequest.ProtoReflect.Descriptor instead.
func (*ReadCommandsByStatusRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{6}
}

func (x *ReadCommandsByStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReadCommandsByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommandsByStatusResponse) Reset() {
	*x = ReadCommandsByStatusResponse{}
	mi := &file_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommandsByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommandsByStatusResponse) ProtoMessage() {}

func (x *ReadCommandsByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommandsByStatusResponse.ProtoReflect.Descriptor instead.
func (*ReadCommandsByStatusResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{7}
}

func (x *ReadCommandsByStatusResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type UpdateCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *int32                 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	DriverId      *string                `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3,oneof" json:"driver_id,omitempty"`
	Path          *string                `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommandRequest) Reset() {
	*x = UpdateCommandRequest{}
	mi := &file_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommandRequest) ProtoMessage() {}

func (x *UpdateCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommandRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCommandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommandRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateCommandRequest) GetDriverId() string {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return ""
}

func (x *UpdateCommandRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type UpdateCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommandResponse) Reset() {
	*x = UpdateCommandResponse{}
	mi := &file_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommandResponse) ProtoMessage() {}

func (x *UpdateCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommandResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x03cat\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"`\n" +
	"\bPosition\x12)\n" +
	"\x03lat\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80V@!\x00\x00\x00\x00\x00\x80V\xc0R\x03lat\x12)\n" +
	"\x03lon\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x11\x00\x00\x00\x00\x00\x80f@!\x00\x00\x00\x00\x00\x80f\xc0R\x03lon\"\x97\x03\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12'\n" +
	"\x0fvalidation_code\x18\x03 \x01(\tR\x0evalidationCode\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x126\n" +
	"\x0forigin_position\x18\x06 \x01(\v2\r.cat.PositionR\x0eoriginPosition\x12@\n" +
	"\x14destination_position\x18\a \x01(\v2\r.cat.PositionR\x13destinationPosition\x12!\n" +
	"\azone_id\x18\b \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06zoneId\x12*\n" +
	"\tdriver_id\x18\t \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bdriverId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_driver_id\"\xbe\x01\n" +
	"\x14CreateCommandRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x126\n" +
	"\x0forigin_position\x18\x03 \x01(\v2\r.cat.PositionR\x0eoriginPosition\x12@\n" +
	"\x14destination_position\x18\x04 \x01(\v2\r.cat.PositionR\x13destinationPosition\"3\n" +
	"\x15CreateCommandResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\x05R\bresponse\"F\n" +
	"\x16ReadAllCommandsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"C\n" +
	"\x17ReadAllCommandsResponse\x12(\n" +
	"\bcommands\x18\x01 \x03(\v2\f.cat.CommandR\bcommands\"5\n" +
	"\x1bReadCommandsByStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"H\n" +
	"\x1cReadCommandsByStatusResponse\x12(\n" +
	"\bcommands\x18\x01 \x03(\v2\f.cat.CommandR\bcommands\"\xb4\x01\n" +
	"\x14UpdateCommandRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\x05H\x00R\x06status\x88\x01\x01\x12*\n" +
	"\tdriver_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x01R\bdriverId\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x04 \x01(\tH\x02R\x04path\x88\x01\x01B\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_driver_idB\a\n" +
	"\x05_path\"?\n" +
	"\x15UpdateCommandResponse\x12&\n" +
	"\acommand\x18\x01 \x01(\v2\f.cat.CommandR\acommand2\xb2\x03\n" +
	"\x0eCommandService\x12\\\n" +
	"\rCreateCommand\x12\x19.cat.CreateCommandRequest\x1a\x1a.cat.CreateCommandResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/commands\x12_\n" +
	"\x0fReadAllCommands\x12\x1b.cat.ReadAllCommandsRequest\x1a\x1c.cat.ReadAllCommandsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/commands\x12~\n" +
	"\x14ReadCommandsByStatus\x12 .cat.ReadCommandsByStatusRequest\x1a!.cat.ReadCommandsByStatusResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/commands/status/{status}\x12a\n" +
	"\rUpdateCommand\x12\x19.cat.UpdateCommandRequest\x1a\x1a.cat.UpdateCommandResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/commands/{id}BR\n" +
	"\acom.catB\fCommandProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03CXX\xaa\x02\x03Cat\xca\x02\x03Cat\xe2\x02\x0fCat\\GPBMetadata\xea\x02\x03Catb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_command_proto_goTypes = []any{
	(*Position)(nil),                     // 0: cat.Position
	(*Command)(nil),                      // 1: cat.Command
	(*CreateCommandRequest)(nil),         // 2: cat.CreateCommandRequest
	(*CreateCommandResponse)(nil),        // 3: cat.CreateCommandResponse
	(*ReadAllCommandsRequest)(nil),       // 4: cat.ReadAllCommandsRequest
	(*ReadAllCommandsResponse)(nil),      // 5: cat.ReadAllCommandsResponse
	(*ReadCommandsByStatusRequest)(nil),  // 6: cat.ReadCommandsByStatusRequest
	(*ReadCommandsByStatusResponse)(nil), // 7: cat.ReadCommandsByStatusResponse
	(*UpdateCommandRequest)(nil),         // 8: cat.UpdateCommandRequest
	(*UpdateCommandResponse)(nil),        // 9: cat.UpdateCommandResponse
}
var file_command_proto_depIdxs = []int32{
	0,  // 0: cat.Command.origin_position:type_name -> cat.Position
	0,  // 1: cat.Command.destination_position:type_name -> cat.Position
	0,  // 2: cat.CreateCommandRequest.origin_position:type_name -> cat.Position
	0,  // 3: cat.CreateCommandRequest.destination_position:type_name -> cat.Position
	1,  // 4: cat.ReadAllCommandsResponse.commands:type_name -> cat.Command
	1,  // 5: cat.ReadCommandsByStatusResponse.commands:type_name -> cat.Command
	1,  // 6: cat.UpdateCommandResponse.command:type_name -> cat.Command
	2,  // 7: cat.CommandService.CreateCommand:input_type -> cat.CreateCommandRequest
	4,  // 8: cat.CommandService.ReadAllCommands:input_type -> cat.ReadAllCommandsRequest
	6,  // 9: cat.CommandService.ReadCommandsByStatus:input_type -> cat.ReadCommandsByStatusRequest
	8,  // 10: cat.CommandService.UpdateCommand:input_type -> cat.UpdateCommandRequest
	3,  // 11: cat.CommandService.CreateCommand:output_type -> cat.CreateCommandResponse
	5,  // 12: cat.CommandService.ReadAllCommands:output_type -> cat.ReadAllCommandsResponse
	7,  // 13: cat.CommandService.ReadCommandsByStatus:output_type -> cat.ReadCommandsByStatusResponse
	9,  // 14: cat.CommandService.UpdateCommand:output_type -> cat.UpdateCommandResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_command_proto_msgTypes[1].OneofWrappers = []any{}
	file_command_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
