// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: slot.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	NextZone      string                 `protobuf:"bytes,3,opt,name=next_zone,json=nextZone,proto3" json:"next_zone,omitempty"`
	InterchangeId string                 `protobuf:"bytes,4,opt,name=interchange_id,json=interchangeId,proto3" json:"interchange_id,omitempty"`
	RelayIndex    int32                  `protobuf:"varint,5,opt,name=relay_index,json=relayIndex,proto3" json:"relay_index,omitempty"`
	ArriveAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=arrive_at,json=arriveAt,proto3" json:"arrive_at,omitempty"`
	SlotAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=slot_at,json=slotAt,proto3" json:"slot_at,omitempty"`
	Wait          *durationpb.Duration   `protobuf:"bytes,8,opt,name=wait,proto3" json:"wait,omitempty"`
	Exchange      *durationpb.Duration   `protobuf:"bytes,9,opt,name=exchange,proto3" json:"exchange,omitempty"`
	AfterExAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=after_ex_at,json=afterExAt,proto3" json:"after_ex_at,omitempty"`
	DriverId      string                 `protobuf:"bytes,11,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	NextDriverId  string                 `protobuf:"bytes,12,opt,name=next_driver_id,json=nextDriverId,proto3" json:"next_driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_slot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{0}
}

func (x *Slot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slot) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Slot) GetNextZone() string {
	if x != nil {
		return x.NextZone
	}
	return ""
}

func (x *Slot) GetInterchangeId() string {
	if x != nil {
		return x.InterchangeId
	}
	return ""
}

func (x *Slot) GetRelayIndex() int32 {
	if x != nil {
		return x.RelayIndex
	}
	return 0
}

func (x *Slot) GetArriveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArriveAt
	}
	return nil
}

func (x *Slot) GetSlotAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SlotAt
	}
	return nil
}

func (x *Slot) GetWait() *durationpb.Duration {
	if x != nil {
		return x.Wait
	}
	return nil
}

func (x *Slot) GetExchange() *durationpb.Duration {
	if x != nil {
		return x.Exchange
	}
	return nil
}

func (x *Slot) GetAfterExAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AfterExAt
	}
	return nil
}

func (x *Slot) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Slot) GetNextDriverId() string {
	if x != nil {
		return x.NextDriverId
	}
	return ""
}

type GetSlotsByZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextZone      string                 `protobuf:"bytes,1,opt,name=next_zone,json=nextZone,proto3" json:"next_zone,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsByZoneRequest) Reset() {
	*x = GetSlotsByZoneRequest{}
	mi := &file_slot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsByZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsByZoneRequest) ProtoMessage() {}

func (x *GetSlotsByZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsByZoneRequest.ProtoReflect.Descriptor instead.
func (*GetSlotsByZoneRequest) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{1}
}

func (x *GetSlotsByZoneRequest) GetNextZone() string {
	if x != nil {
		return x.NextZone
	}
	return ""
}

func (x *GetSlotsByZoneRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetSlotsByZoneRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSlotsByInterchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterchangeId string                 `protobuf:"bytes,1,opt,name=interchange_id,json=interchangeId,proto3" json:"interchange_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsByInterchangeRequest) Reset() {
	*x = GetSlotsByInterchangeRequest{}
	mi := &file_slot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsByInterchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsByInterchangeRequest) ProtoMessage() {}

func (x *GetSlotsByInterchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsByInterchangeRequest.ProtoReflect.Descriptor instead.
func (*GetSlotsByInterchangeRequest) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{2}
}

func (x *GetSlotsByInterchangeRequest) GetInterchangeId() string {
	if x != nil {
		return x.InterchangeId
	}
	return ""
}

func (x *GetSlotsByInterchangeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetSlotsByInterchangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSlotsByDriverIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsByDriverIDRequest) Reset() {
	*x = GetSlotsByDriverIDRequest{}
	mi := &file_slot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsByDriverIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsByDriverIDRequest) ProtoMessage() {}

func (x *GetSlotsByDriverIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsByDriverIDRequest.ProtoReflect.Descriptor instead.
func (*GetSlotsByDriverIDRequest) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{3}
}

func (x *GetSlotsByDriverIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetSlotsByDriverIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*Slot                `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsResponse) Reset() {
	*x = GetSlotsResponse{}
	mi := &file_slot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsResponse) ProtoMessage() {}

func (x *GetSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetSlotsResponse) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{4}
}

func (x *GetSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_slot_proto protoreflect.FileDescriptor

const file_slot_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"slot.proto\x12\x03cat\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x95\x04\n" +
	"\x04Slot\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12'\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tcommandId\x12%\n" +
	"\tnext_zone\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bnextZone\x12/\n" +
	"\x0einterchange_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rinterchangeId\x12\x1f\n" +
	"\vrelay_index\x18\x05 \x01(\x05R\n" +
	"relayIndex\x127\n" +
	"\tarrive_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\barriveAt\x123\n" +
	"\aslot_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06slotAt\x12-\n" +
	"\x04wait\x18\b \x01(\v2\x19.google.protobuf.DurationR\x04wait\x125\n" +
	"\bexchange\x18\t \x01(\v2\x19.google.protobuf.DurationR\bexchange\x12:\n" +
	"\vafter_ex_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tafterExAt\x12\x1b\n" +
	"\tdriver_id\x18\v \x01(\tR\bdriverId\x12$\n" +
	"\x0enext_driver_id\x18\f \x01(\tR\fnextDriverId\"\x81\x01\n" +
	"\x15GetSlotsByZoneRequest\x12%\n" +
	"\tnext_zone\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bnextZone\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x06offset\x12 \n" +
	"\x05limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x01R\x05limit\"\x92\x01\n" +
	"\x1cGetSlotsByInterchangeRequest\x12/\n" +
	"\x0einterchange_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rinterchangeId\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x06offset\x12 \n" +
	"\x05limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x01R\x05limit\"^\n" +
	"\x19GetSlotsByDriverIDRequest\x12\x1f\n" +
	"\x06offset\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x06offset\x12 \n" +
	"\x05limit\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x01R\x05limit\"3\n" +
	"\x10GetSlotsResponse\x12\x1f\n" +
	"\x05slots\x18\x01 \x03(\v2\t.cat.SlotR\x05slots2\xf7\x02\n" +
	"\vSlotService\x12m\n" +
	"\x0eGetSlotsByZone\x12\x1a.cat.GetSlotsByZoneRequest\x1a\x15.cat.GetSlotsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/abyssin/slots/zone/{zone_id}\x12\x89\x01\n" +
	"\x15GetSlotsByInterchange\x12!.cat.GetSlotsByInterchangeRequest\x1a\x15.cat.GetSlotsResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/abyssin/slots/interchange/{interchange_id}\x12m\n" +
	"\x12GetSlotsByDriverID\x12\x1e.cat.GetSlotsByDriverIDRequest\x1a\x15.cat.GetSlotsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/abyssin/slots/driverBO\n" +
	"\acom.catB\tSlotProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03CXX\xaa\x02\x03Cat\xca\x02\x03Cat\xe2\x02\x0fCat\\GPBMetadata\xea\x02\x03Catb\x06proto3"

var (
	file_slot_proto_rawDescOnce sync.Once
	file_slot_proto_rawDescData []byte
)

func file_slot_proto_rawDescGZIP() []byte {
	file_slot_proto_rawDescOnce.Do(func() {
		file_slot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slot_proto_rawDesc), len(file_slot_proto_rawDesc)))
	})
	return file_slot_proto_rawDescData
}

var file_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_slot_proto_goTypes = []any{
	(*Slot)(nil),                         // 0: cat.Slot
	(*GetSlotsByZoneRequest)(nil),        // 1: cat.GetSlotsByZoneRequest
	(*GetSlotsByInterchangeRequest)(nil), // 2: cat.GetSlotsByInterchangeRequest
	(*GetSlotsByDriverIDRequest)(nil),    // 3: cat.GetSlotsByDriverIDRequest
	(*GetSlotsResponse)(nil),             // 4: cat.GetSlotsResponse
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),          // 6: google.protobuf.Duration
}
var file_slot_proto_depIdxs = []int32{
	5, // 0: cat.Slot.arrive_at:type_name -> google.protobuf.Timestamp
	5, // 1: cat.Slot.slot_at:type_name -> google.protobuf.Timestamp
	6, // 2: cat.Slot.wait:type_name -> google.protobuf.Duration
	6, // 3: cat.Slot.exchange:type_name -> google.protobuf.Duration
	5, // 4: cat.Slot.after_ex_at:type_name -> google.protobuf.Timestamp
	0, // 5: cat.GetSlotsResponse.slots:type_name -> cat.Slot
	1, // 6: cat.SlotService.GetSlotsByZone:input_type -> cat.GetSlotsByZoneRequest
	2, // 7: cat.SlotService.GetSlotsByInterchange:input_type -> cat.GetSlotsByInterchangeRequest
	3, // 8: cat.SlotService.GetSlotsByDriverID:input_type -> cat.GetSlotsByDriverIDRequest
	4, // 9: cat.SlotService.GetSlotsByZone:output_type -> cat.GetSlotsResponse
	4, // 10: cat.SlotService.GetSlotsByInterchange:output_type -> cat.GetSlotsResponse
	4, // 11: cat.SlotService.GetSlotsByDriverID:output_type -> cat.GetSlotsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_slot_proto_init() }
func file_slot_proto_init() {
	if File_slot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slot_proto_rawDesc), len(file_slot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slot_proto_goTypes,
		DependencyIndexes: file_slot_proto_depIdxs,
		MessageInfos:      file_slot_proto_msgTypes,
	}.Build()
	File_slot_proto = out.File
	file_slot_proto_goTypes = nil
	file_slot_proto_depIdxs = nil
}
