// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: transfer_session.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTransferSessionCodeByCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferSessionCodeByCommandRequest) Reset() {
	*x = GetTransferSessionCodeByCommandRequest{}
	mi := &file_transfer_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferSessionCodeByCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferSessionCodeByCommandRequest) ProtoMessage() {}

func (x *GetTransferSessionCodeByCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferSessionCodeByCommandRequest.ProtoReflect.Descriptor instead.
func (*GetTransferSessionCodeByCommandRequest) Descriptor() ([]byte, []int) {
	return file_transfer_session_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransferSessionCodeByCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetTransferSessionCodeByCommandResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresInSeconds int32                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransferSessionCodeByCommandResponse) Reset() {
	*x = GetTransferSessionCodeByCommandResponse{}
	mi := &file_transfer_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferSessionCodeByCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferSessionCodeByCommandResponse) ProtoMessage() {}

func (x *GetTransferSessionCodeByCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferSessionCodeByCommandResponse.ProtoReflect.Descriptor instead.
func (*GetTransferSessionCodeByCommandResponse) Descriptor() ([]byte, []int) {
	return file_transfer_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransferSessionCodeByCommandResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetTransferSessionCodeByCommandResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTransferSessionCodeByCommandResponse) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

var File_transfer_session_proto protoreflect.FileDescriptor

const file_transfer_session_proto_rawDesc = "" +
	"\n" +
	"\x16transfer_session.proto\x12\x03cat\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"Q\n" +
	"&GetTransferSessionCodeByCommandRequest\x12'\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tcommandId\"\xa8\x01\n" +
	"'GetTransferSessionCodeByCommandResponse\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x04\x18\n" +
	"R\x04code\x12'\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tsessionId\x125\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x10expiresInSeconds2\xd8\x01\n" +
	"\x16TransferSessionService\x12\xbd\x01\n" +
	"\x1fGetTransferSessionCodeByCommand\x12+.cat.GetTransferSessionCodeByCommandRequest\x1a,.cat.GetTransferSessionCodeByCommandResponse\"?\x82\xd3\xe4\x93\x029\x127/v1/abyssin/transfer-sessions/command/{command_id}/codeBZ\n" +
	"\acom.catB\x14TransferSessionProtoP\x01Z\rmau/pkg/pb;pb\xa2\x02\x03CXX\xaa\x02\x03Cat\xca\x02\x03Cat\xe2\x02\x0fCat\\GPBMetadata\xea\x02\x03Catb\x06proto3"

var (
	file_transfer_session_proto_rawDescOnce sync.Once
	file_transfer_session_proto_rawDescData []byte
)

func file_transfer_session_proto_rawDescGZIP() []byte {
	file_transfer_session_proto_rawDescOnce.Do(func() {
		file_transfer_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_session_proto_rawDesc), len(file_transfer_session_proto_rawDesc)))
	})
	return file_transfer_session_proto_rawDescData
}

var file_transfer_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transfer_session_proto_goTypes = []any{
	(*GetTransferSessionCodeByCommandRequest)(nil),  // 0: cat.GetTransferSessionCodeByCommandRequest
	(*GetTransferSessionCodeByCommandResponse)(nil), // 1: cat.GetTransferSessionCodeByCommandResponse
}
var file_transfer_session_proto_depIdxs = []int32{
	0, // 0: cat.TransferSessionService.GetTransferSessionCodeByCommand:input_type -> cat.GetTransferSessionCodeByCommandRequest
	1, // 1: cat.TransferSessionService.GetTransferSessionCodeByCommand:output_type -> cat.GetTransferSessionCodeByCommandResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transfer_session_proto_init() }
func file_transfer_session_proto_init() {
	if File_transfer_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_session_proto_rawDesc), len(file_transfer_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_session_proto_goTypes,
		DependencyIndexes: file_transfer_session_proto_depIdxs,
		MessageInfos:      file_transfer_session_proto_msgTypes,
	}.Build()
	File_transfer_session_proto = out.File
	file_transfer_session_proto_goTypes = nil
	file_transfer_session_proto_depIdxs = nil
}
